project:
  type: book
  output-dir: docs
  preview:
    port: 7771
    browser: false
  resources:
    - "data/*.mp3"
  render:
    - "*.qmd"
    - "!*.Rmd"
    - "!to_do.qmd"

lang: ko-KR

book:
  title: "데이터 기반 디자인과 A/B 테스팅"
  reader-mode: true
  subtitle: "데이터 기반 디자인과 A/B 테스팅의 핵심 개념과 사례
모바일 앱 디자인 대상의 단계별 실습 과제 수록 "
  page-footer:
    left: |
      이 책은 소프트웨어 카펜트리 "R for Reproducible Scientific Analysis"를 번역한 것이 포함되어 있습니다.
    right: |
      순수하게 <a href="https://quarto.org/">쿼토(Quarto)</a>로 제작되었습니다.
  repo-url: https://github.com/hyunjhinlee/DataDrivenDesign
  repo-branch: main_ym
  repo-actions: [edit, issue]
  author:
    - name: "이현진"
      affiliations: "홍익대학교"
  date: last-modified
  date-format: "YYYY년 MM월 DD일"
  chapters:
    - index.qmd
    - part: "**part 1. UX 디자인과 데이터**"
      chapters:
        - "part 1. UX 디자인과 데이터.qmd"
        - "ch1 UX 디자인의 오늘과 변화의 방향.qmd"
        - "ch2 UX 디자인과 데이터, AI.qmd"
        - "ch3 데이터 기반 디자인 (Data Driven Design).qmd"
        
    - part: "**part 2. 디자인 리서치를 위한 탐구적 데이터 분석**"
      chapters:
        - "part 2. 디자인 리서치를 위한 탐구적 데이터 분석.qmd"
        - "ch1 디자인 리서치와 탐구적 데이터 분석.qmd"
        - "ch2 디자인 리서치를 위한 탐구적 데이터 분석.qmd"
        - "ch3 디자인 리서치를 위한 탐구적 데이터 분석.qmd"
        - "ch4 EDA를 위한 데이터 분석 도구들.qmd"
        - "ch5 Lean UX 프로세스와 데이터 기반 디자인.qmd"

        
    - references.qmd


format:
  html:
    theme:
      light: [cosmo, r2bit.scss]
    mermaid:
      theme: neutral
    number-depth: 3
    number-sections: false
    colorlinks: true
    code-overflow: wrap
    code-link: true
    author-meta: "이현진"
    callout-appearance: simple
    tbl-cap-location: bottom
    lst-cap-location: bottom
    bibliography: references.bib  # <-- 여기에 bibliography 항목 추가


webr:
  packages: ["stringr", "dplyr"]

engine: knitr

knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: true
    code-overflow: wrap
    fig-crop: false
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

editor_options:
  chunk_output_type: console

editor:
  source: true