# ch1. 디자인 리서치와 탐구적 데이터 분석 (EDA:Exploratory Data Analysis)

### 디자인 리서치란

디자인 리서치란 디자이너가 디자인 과정에서 디자인 문제를 이해하고, 주요 의사결정을 하기 위해 여러 관련 데이터를 수집, 분석, 모델링하는 과정을 말합니다. UX 디자인의 특징에 다양한 디자인 리서치 방법론이 포함될 정도로 디자인 리서치는 UX 디자인에서 매우 중요한 과정입니다. 디자인 리서치 대상인 데이터는 보통 사용자와 관련한 데이터, 프로젝트와 관련된 데이터, 그리고 프로젝트에 영향을 주는 시대나 사회, 기술의 변화에 관련한 데이터들이 포함됩니다. 디자이너는 이러한 데이터들을 적절한 방법으로 이해하고 분석하여 디자인 의사결정에 필요한 중간 산출물을 도출합니다. 디자인 리서치 과정을 통하여 디자이너가 만들어내는 중간 산출물 정보는 사용자 조사나 경쟁 제품 분석 보고서, 어피니티 다이어그램, 사용자 페르소나, 사용자 여정 지도, 콘텐츠 정보 구조도, 스토리보드, 서비스 프로토타입 등입니다. 이렇게 생성된 정보들은 디자인 해결안의 방향과 내용을 결정하는 근거가 됩니다. 그러므로 디자인 리서치가 디자인 결과물의 성공을 좌우한다고 볼 수도 있습니다. 결과적으로, 디자인 리서치는 사용자의 만족도를 높이고 비즈니스 목표를 달성하는 데 중요한 역할을 합니다.

### 탐구적 데이터 분석이란

탐구적 데이터 분석(EDA, Explanatory DataAnalysis)은 데이터 과학의 데이터 분석 방법 중의 하나로, 데이터 시각화 기술을 사용하여 데이터의 특징을 탐지하고 트렌드나 패턴을 확인하여 인사이트를 발견하는 데이터 분석 방법입니다. 탐구적 분석은 데이터 분석의 초기 단계에서 가장 많이 사용되고, 깊은 통찰력을 제공하며 분석 결과를 시각적으로 제시함으로써 비전문가들도 내용을 쉽게 이해할 수 있게 하는 특징이 있습니다. 데이터 분석 소프트웨어 플랫폼 기업인 Posit의 수석 과학자인 해들리 위컴(Hadley Wichham)은 탐구적 데이터 분석 방법을 통하여 각 변수 별로 일반적인 값과 비정상적인 값의 상태, 변수 간의 상관관계와 구조를 확인할 수 있다고 하였습니다. 그는 저서에서 탐구적 데이터 분석 과정에 대하여 \[그림 4\]와 같이 표현했는데, 먼저 데이터를 가져오기 하여(Import) 정리한(Tidy) 뒤, 데이터를 분석에 적합한 형태로 변형하고(Transform), 데이터 시각화(Visualize)와 데이터 모델링(Model)을 반복적으로 수행하여 목표한 분석 결과가 나오면, 분석 내용을 이해하기 좋은 형태로 소통한다고(Communicate) 설명합니다.

![\[그림 3\] 탐구적 데이터 분석 프로세스 다이어그램(9)](ch1%20디자인%20리서치와%20탐구적%20데이터%20분석/eda.png)

### 디자인 리서치와 탐구적 데이터 분석의 만남

탐구적 분석에서 데이터(문제)의 현황을 탐지하고 트렌드나 패턴을 통하여 인사이트를 발견한다는 것은 더블 다이아몬드 디자인 프로세스 모델의 앞부분인 문제의 발견과 정의 단계에서 하는 활동과 매우 유사한 방법입니다. 다만 디자이너는 이 작업을 다양한 형식(비정형)의 자료를 대상으로 하고 통계 기법을 포함하여 정량, 정성, 직관적인 연구 기법을 다양하게 사용하여 수행하지만, 데이터 과학에서는 대상 데이터 형식을 정제하여 통계적 분석과 통계적 시각화 기법으로 결과를 도출한다는 점이 다릅니다.

그리고 위컴이 제시한 \[그림 4\]의 ‘탐구적 데이터 분석 프로세스 다이어그램’에는 데이터의 탐색이 의미 있는 인사이트를 발견할 때까지 반복적으로 수행되는 속성이 표현되어 있는데, 이는 디자인 프로세스의 반복적 속성과도 상통합니다. 그래서 교재의 데이터 기반 디자인 실습과제에서는 디자인 리서치 과정에서 탐구적 데이터 분석 방법을 적극적으로 활용하여 프로젝트를 진행하고자 합니다. 앞으로의 디자인 리서치 실습 과제에서 데이터 시각화 그래프들을 도출하거나, 이미 공개된 분석 보고서의 그래프들을 수집하여 그래프들의 인사이트를 도출하는 탐구적 데이터 분석 방법을 사용할 예정입니다.

(문헌 9)Hadley Wichham, Garrett. Grolemund, 『R for Data Science(2e.)』, (2023), <https://r4ds.hadley.nz/intro>
