# ch1. 실습과제의 디자인 프로세스, 주제 선정

### 실습 과제의 개요 및 디자인 프로세스

지금까지 이론적으로 공부한 데이터 기반 디자인 개념을 실습 프로젝트를 통하여 몸에 익혀봅시다. 우리가 진행할 실습 프로젝트는 관심 주제의 데이터를 선택하여 데이터를 해석하고, 해당 데이터 인사이트를 디자인에 반영할 서비스(기존 디자인, A디자인)를 선정한 뒤, 이 서비스를 데이터 기반 디자인 방법론을 통하여 개선 디자인(B 디자인)으로 제안하고, 개선 여부를 A/B 테스팅으로 검증하는 과제입니다. 개선 디자인에서 개선되지 못한 부분들은 다시 업데이트한 디자인(최종 디자인, B’ 디자인)을 제안하며 과제를 마무리합니다.

앞으로 우리는 A 디자인, B 디자인, B’ 디자인이라는 용어를 매우 자주 사용하게 될텐데요, A 디자인은 타겟 서비스, 즉 우리가 새로 디자인할 서비스의 기존 디자인, 현재 운영중인 디자인을 말합니다. 우리는 데이터 기반 디자인 방법론으로 A 디자인의 문제들을 연구하여 새로운 B 디자인을 해결안으로 제안할 예정입니다. 그리고 B’ 디자인은 A, B 디자인에 대한 디자인 개선 여부를 A/B 테스팅으로 검증한 뒤, 개선되지 않았다고 평가된 부분들에 대하여 디자인 수정한 해결안을 B’ 디자인으로 지칭할 예정입니다. B’ 디자인에 대하여도 A/B 테스팅을 실시하여 개선 여부를 검증하는 과정을 반복적으로 수행하여 지속적으로 서비스를 개선해 나가야하지만, 한 학기의 제한된 시간 여건에서 B’ 디자인을 제안하는 것으로 학기 과제를 마치게 됩니다.

실습 과제의 진행 프로세스는 \[그림 23\]과 같이 더블 다이아몬드 디자인 프로세스와 린 UX 디자인 프로세스의 융합으로 진행됩니다.

실습 과제의 내용을 주 별 활동 단위로 나누어 정리하면 다음과 같습니다.

-   먼저 관심 데이터와 타겟 서비스를 선정해서 관련 데이터를 조사 분석하여 데이터 인사이트를 도출하고,
-   또 한 방향으로는 타겟 서비스에 대한 디자인 분석을 실시하여 디자인 인사이트를 발견합니다.
-   양 방향에서 수집한 디자인 인사이트를 종합하여 타겟 서비스에 대한 문제의 구조와 KPI를 선정하고
-   KPI를 개선할 디자인 콘셉트(가설)를 도출하여
-   이를 반영한 개선 디자인과 최소기능제품(MVP)을 제작합니다.
-   MVP 디자인에 대한 사용자 반응을 설문 조사하여 A/B 테스트를 실시하고, 개선 디자인이 목표한 KPI를 달성하였는지 검증합니다.
-   목표 KPI를 달성한 디자인 속성을 반영하고, 목표를 달성하지 못한 디자인 속성은 원인과 해결 방안을 분석, 반영하여 최종 디자인을 완성합니다.

![\[그림 22\] 실습 과제의 디자인 프로세스 : Double Diamond Design Process + Lean UX Process (실습 주차 표기는 참고 사항이며, 최종 디자인(B’ 디자인)의 개발 과정은 개선 디자인(B디자인)의 개발 과정을 반복함.)](img/fig22.png)

이제 부터는 위의 디자인 프로세스를 차근 차근 따라가면서 실습과 이론을 병행하여 설명하도록 하겠습니다. 수업에서 프로젝트 조 구성 3인 1조를 기본으로 하고 있으며, 실습 과제를 주 단위로 수행하고 있습니다.

### 프로젝트 주제 선정

일반적으로 디자인의 프로젝트를 시작할 때는 먼저 프로젝트의 주제가 정해지고, 이에 대한 데이터 리서치를 실시하는게 정상적인 방법일 것입니다. 특정 프로젝트의 주제와 관련한 데이터를 쉽게 수집할 수 있다면, 이렇게 하는 것이 맞지만, 우리는 학교에서 실습 과제를 수행하는 상황이라서, 알고 싶은 주제의 데이터를 직접 수집하는 것이 어렵습니다. 보통 기업 서비스와 관련된 데이터는 공개 되지 않지요. 또 관련 데이터를 수집한 자료가 아예 없거나, 짧은 시간에 충분한 규모의 데이터를 직접 수집하는 것이 불가능한 경우가 대부분입니다. 데이터 기반 디자인을 하기위한 데이터가 확보가 쉽지 않은 것입니다.

그래서 우리 실습에서는 순서를 바꾸어, 우리가 수집, 분석 가능하도록 공개된 데이터를 먼저 확보하고, 그 데이터와 관련한 서비스를 프로젝트 주제로 정하여 진행합니다. 그래서 아래와 같은 국내 데이터 제공 서비스들을 둘러보고, 관심있는 주제나 사용자 경험과 연계 가능한 데이터들을 선정하고, 이 데이터의 분석 인사이트가 적용될 수 있는 서비스를 선택하여 타겟 서비스(A 디자인)로 정합니다. 그래서 디자인 프로젝트를 정의하는 프로젝트 선언문을(Project Statement) 조금 나중에 결정하게 됩니다. 주어진 여건에서 데이터 큐레이션을 하기위한 현실적인 실습 방법으로 이해하기 바랍니다.

국내의 공공 데이터 제공 서비스는 통합 데이터 지도, MDIS 마이크로데이터 통합서비스, 서울열린데이터광장 등이 있습니다. 이들 서비스는 직접 분석을 해야하는 원본 데이터(raw data)도 제공하고, 원본 데이터를 분석한 가공 데이터나 시각화 그래프, 정리된 데이터 분석 보고서도 제공하고 있어서, 필요에 따라 다양한 수준의 데이터 가공이 가능합니다. 특히 우리 수업은 데이터 분석 기술을 학습하는 수업이 아니기 때문에 이미 분석된 데이터를 사용하는 비중이 높습니다. 예를들어 결혼과 관련하여 인구 통계 분석 데이터, 혼수 소비 시장 데이터, 신혼 부부를 위한 금융 서비스 데이터들이나 분석 보고서가 수집될 수 있다면 웨딩플래너 서비스를 타겟 앱 서비스로 선정하여 디자인 제안 프로젝트를 진행할 수 있습니다. 앞서의 탐구적 데이터 분석 사례에서 미세먼지 측정 데이터와 날씨 데이터를 확보하여 미세먼지 정보 서비스 앱을 디자인 제안한 것도 같은 맥락입니다.

-   데이터 검색 및 관심 데이터 조사를 위한 국내 데이터 서비스들 (22)(23)(24)

[통합 데이터지도 - 공공 민간 빅데이터 통합 검색](https://www.bigdata-map.kr)

[MDIS 마이크로데이터 통합서비스](https://mdis.kostat.go.kr/index.do)

[열린데이터광장 메인](https://data.seoul.go.kr)

### 실습과제 2 : 실습 과제의 타겟 서비스(A 디자인) 제안

위에 제시한 공공 데이터 서비스나 보도 자료, 논문 등을 활용하여 관심 데이터 주제를 선정해주세요. 수집한 데이터들을 분석하거나 분석된 자료를 해석하여 어떤 이슈나 인사이트가 발견되는지 수집하고, 발견한 인사이트를 활용할 수 있는 앱 서비스를 제안해주세요. 적절한 앱 서비스를 선정하기 위해 여러 개의 (3가지 이상) 서비스를 비교하여 데이터 리서치와 개선 디자인 제안 실습 과제에 적합한 앱을 제시하기 바랍니다.

수집한 데이터는 자세히 분석할 수 있으면 좋지만, 현재 여건에서 가능한 일부만 진행해도 됩니다. 데이터 수집 및 분석은 다음 과제에서도 2-3주간 지속적으로 추가 진행할 것이므로, 완성도가 부족해도 타겟 서비스를 선정할 수 있을 정도로만 우선 진행합니다.

수집한 데이터(수집 출처, 데이터 형식 포함)와 데이터의 인사이트, 제안하는 기존 서비스(A 서비스)의 내용과 선정 이유를 논리적으로 구성하여 2-3페이지 분량의 제안서를 작성합니다.

### 실습과제 2 Check Point!

주제 선정 이후의 실습 과정을 용이하게 하기 위하여 아래의 요소들도 고려하기 바랍니다.

-   관심 주제의 콘텐츠/ 서비스 내용을 분석하여 데이터 인사이트를 낼 수 있는 데이터나 데이터 시각화 자료가 존재해야함. (있다고 가정하면 안됨)
-   생각하는 서비스의 내용에 대하여 기존에 출시되어 있는 서비스(A안)가 존재해야함. A서비스와 B서비스를 합쳐서 기존에 없던 C서비스를 만드는 프로젝트는 안됨 (A/B 테스트 불가, 서비스 내용이 다르면 디자인을 비교할 수 없음)
-   사회 정책을 개발하거나 홍보하는 주제가 아니라 개인의 사용자 경험(인지, 의사결정, 행위)을 개선하는 주제여야함. 의견을 묻는 것이 아닌 행동 변화를 확인하는 주제여야 함.
-   타겟 서비스의 내용이나 디자인에 대하여 설문으로 사용자 피드백을 얻는 것이 가능해야함. 사용자 의견을 얻기 위하여 서비스 경험 시간이 많이 필요한 서비스는 지양함.(예를 들어 학습 경험은 학습 시간, 러닝 커브가 필요하여 짧은 시간에 앱 화면을 보는 경험 만으로는 평가가 어려움)
-   어떻게 서비스를 테스트 할 것인가에 대한 고려가 필요함. 외국인 대상의 서비스면 외국인 대상으로, 아동 대상의 서비스면 아동 대상으로 테스트 해야하므로, 테스트를 위하여 60명 이상의 평가 인원 참여가(A테스트 30명, B테스트 30명) 가능한 주제를 선택함. 평가 참여 인원은 많을수록 좋음.

(문헌22) 통합 데이터지도-공공 민간 빅데이터 통합검색 https://www.bigdata-map.or

(문헌23) MDIS 마이크로데이터 통합서비스 https://mdis.kostat.go.kr

(문헌24) 서울 열린데이터광장 https://data.seoul.go.kr
# ch1. 실습과제의 디자인 프로세스, 주제 선정

### 실습 과제의 개요 및 디자인 프로세스

지금까지 이론적으로 공부한 데이터 기반 디자인 개념을 실습 프로젝트를 통하여 몸에 익혀봅시다. 우리가 진행할 실습 프로젝트는 관심 주제의 데이터를 선택하여 데이터를 해석하고, 해당 데이터 인사이트를 디자인에 반영할 서비스(기존 디자인, A디자인)를 선정한 뒤, 이 서비스를 데이터 기반 디자인 방법론을 통하여 개선 디자인(B 디자인)으로 제안하고, 개선 여부를 A/B 테스팅으로 검증하는 과제입니다. 개선 디자인에서 개선되지 못한 부분들은 다시 업데이트한 디자인(최종 디자인, B’ 디자인)을 제안하며 과제를 마무리합니다.

앞으로 우리는 A 디자인, B 디자인, B’ 디자인이라는 용어를 매우 자주 사용하게 될텐데요, A 디자인은 타겟 서비스, 즉 우리가 새로 디자인할 서비스의 기존 디자인, 현재 운영중인 디자인을 말합니다. 우리는 데이터 기반 디자인 방법론으로 A 디자인의 문제들을 연구하여 새로운 B 디자인을 해결안으로 제안할 예정입니다. 그리고 B’ 디자인은 A, B 디자인에 대한 디자인 개선 여부를 A/B 테스팅으로 검증한 뒤, 개선되지 않았다고 평가된 부분들에 대하여 디자인 수정한 해결안을 B’ 디자인으로 지칭할 예정입니다. B’ 디자인에 대하여도 A/B 테스팅을 실시하여 개선 여부를 검증하는 과정을 반복적으로 수행하여 지속적으로 서비스를 개선해 나가야하지만, 한 학기의 제한된 시간 여건에서 B’ 디자인을 제안하는 것으로 학기 과제를 마치게 됩니다.

실습 과제의 진행 프로세스는 \[그림 23\]과 같이 더블 다이아몬드 디자인 프로세스와 린 UX 디자인 프로세스의 융합으로 진행됩니다.

실습 과제의 내용을 주 별 활동 단위로 나누어 정리하면 다음과 같습니다.

-   먼저 관심 데이터와 타겟 서비스를 선정해서 관련 데이터를 조사 분석하여 데이터 인사이트를 도출하고,
-   또 한 방향으로는 타겟 서비스에 대한 디자인 분석을 실시하여 디자인 인사이트를 발견합니다.
-   양 방향에서 수집한 디자인 인사이트를 종합하여 타겟 서비스에 대한 문제의 구조와 KPI를 선정하고
-   KPI를 개선할 디자인 콘셉트(가설)를 도출하여
-   이를 반영한 개선 디자인과 최소기능제품(MVP)을 제작합니다.
-   MVP 디자인에 대한 사용자 반응을 설문 조사하여 A/B 테스트를 실시하고, 개선 디자인이 목표한 KPI를 달성하였는지 검증합니다.
-   목표 KPI를 달성한 디자인 속성을 반영하고, 목표를 달성하지 못한 디자인 속성은 원인과 해결 방안을 분석, 반영하여 최종 디자인을 완성합니다.

![\[그림 22\] 실습 과제의 디자인 프로세스 : Double Diamond Design Process + Lean UX Process (실습 주차 표기는 참고 사항이며, 최종 디자인(B’ 디자인)의 개발 과정은 개선 디자인(B디자인)의 개발 과정을 반복함.)](img/fig22.png)

이제 부터는 위의 디자인 프로세스를 차근 차근 따라가면서 실습과 이론을 병행하여 설명하도록 하겠습니다. 수업에서 프로젝트 조 구성 3인 1조를 기본으로 하고 있으며, 실습 과제를 주 단위로 수행하고 있습니다.

### 프로젝트 주제 선정

일반적으로 디자인의 프로젝트를 시작할 때는 먼저 프로젝트의 주제가 정해지고, 이에 대한 데이터 리서치를 실시하는게 정상적인 방법일 것입니다. 특정 프로젝트의 주제와 관련한 데이터를 쉽게 수집할 수 있다면, 이렇게 하는 것이 맞지만, 우리는 학교에서 실습 과제를 수행하는 상황이라서, 알고 싶은 주제의 데이터를 직접 수집하는 것이 어렵습니다. 보통 기업 서비스와 관련된 데이터는 공개 되지 않지요. 또 관련 데이터를 수집한 자료가 아예 없거나, 짧은 시간에 충분한 규모의 데이터를 직접 수집하는 것이 불가능한 경우가 대부분입니다. 데이터 기반 디자인을 하기위한 데이터가 확보가 쉽지 않은 것입니다.

그래서 우리 실습에서는 순서를 바꾸어, 우리가 수집, 분석 가능하도록 공개된 데이터를 먼저 확보하고, 그 데이터와 관련한 서비스를 프로젝트 주제로 정하여 진행합니다. 그래서 아래와 같은 국내 데이터 제공 서비스들을 둘러보고, 관심있는 주제나 사용자 경험과 연계 가능한 데이터들을 선정하고, 이 데이터의 분석 인사이트가 적용될 수 있는 서비스를 선택하여 타겟 서비스(A 디자인)로 정합니다. 그래서 디자인 프로젝트를 정의하는 프로젝트 선언문을(Project Statement) 조금 나중에 결정하게 됩니다. 주어진 여건에서 데이터 큐레이션을 하기위한 현실적인 실습 방법으로 이해하기 바랍니다.

국내의 공공 데이터 제공 서비스는 통합 데이터 지도, MDIS 마이크로데이터 통합서비스, 서울열린데이터광장 등이 있습니다. 이들 서비스는 직접 분석을 해야하는 원본 데이터(raw data)도 제공하고, 원본 데이터를 분석한 가공 데이터나 시각화 그래프, 정리된 데이터 분석 보고서도 제공하고 있어서, 필요에 따라 다양한 수준의 데이터 가공이 가능합니다. 특히 우리 수업은 데이터 분석 기술을 학습하는 수업이 아니기 때문에 이미 분석된 데이터를 사용하는 비중이 높습니다. 예를들어 결혼과 관련하여 인구 통계 분석 데이터, 혼수 소비 시장 데이터, 신혼 부부를 위한 금융 서비스 데이터들이나 분석 보고서가 수집될 수 있다면 웨딩플래너 서비스를 타겟 앱 서비스로 선정하여 디자인 제안 프로젝트를 진행할 수 있습니다. 앞서의 탐구적 데이터 분석 사례에서 미세먼지 측정 데이터와 날씨 데이터를 확보하여 미세먼지 정보 서비스 앱을 디자인 제안한 것도 같은 맥락입니다.

-   데이터 검색 및 관심 데이터 조사를 위한 국내 데이터 서비스들 (22)(23)(24)

[통합 데이터지도 - 공공 민간 빅데이터 통합 검색](https://www.bigdata-map.kr)

[MDIS 마이크로데이터 통합서비스](https://mdis.kostat.go.kr/index.do)

[열린데이터광장 메인](https://data.seoul.go.kr)

### 실습과제 2 : 실습 과제의 타겟 서비스(A 디자인) 제안

위에 제시한 공공 데이터 서비스나 보도 자료, 논문 등을 활용하여 관심 데이터 주제를 선정해주세요. 수집한 데이터들을 분석하거나 분석된 자료를 해석하여 어떤 이슈나 인사이트가 발견되는지 수집하고, 발견한 인사이트를 활용할 수 있는 앱 서비스를 제안해주세요. 적절한 앱 서비스를 선정하기 위해 여러 개의 (3가지 이상) 서비스를 비교하여 데이터 리서치와 개선 디자인 제안 실습 과제에 적합한 앱을 제시하기 바랍니다.

수집한 데이터는 자세히 분석할 수 있으면 좋지만, 현재 여건에서 가능한 일부만 진행해도 됩니다. 데이터 수집 및 분석은 다음 과제에서도 2-3주간 지속적으로 추가 진행할 것이므로, 완성도가 부족해도 타겟 서비스를 선정할 수 있을 정도로만 우선 진행합니다.

수집한 데이터(수집 출처, 데이터 형식 포함)와 데이터의 인사이트, 제안하는 기존 서비스(A 서비스)의 내용과 선정 이유를 논리적으로 구성하여 2-3페이지 분량의 제안서를 작성합니다.

### 실습과제 2 Check Point!

주제 선정 이후의 실습 과정을 용이하게 하기 위하여 아래의 요소들도 고려하기 바랍니다.

-   관심 주제의 콘텐츠/ 서비스 내용을 분석하여 데이터 인사이트를 낼 수 있는 데이터나 데이터 시각화 자료가 존재해야함. (있다고 가정하면 안됨)
-   생각하는 서비스의 내용에 대하여 기존에 출시되어 있는 서비스(A안)가 존재해야함. A서비스와 B서비스를 합쳐서 기존에 없던 C서비스를 만드는 프로젝트는 안됨 (A/B 테스트 불가, 서비스 내용이 다르면 디자인을 비교할 수 없음)
-   사회 정책을 개발하거나 홍보하는 주제가 아니라 개인의 사용자 경험(인지, 의사결정, 행위)을 개선하는 주제여야함. 의견을 묻는 것이 아닌 행동 변화를 확인하는 주제여야 함.
-   타겟 서비스의 내용이나 디자인에 대하여 설문으로 사용자 피드백을 얻는 것이 가능해야함. 사용자 의견을 얻기 위하여 서비스 경험 시간이 많이 필요한 서비스는 지양함.(예를 들어 학습 경험은 학습 시간, 러닝 커브가 필요하여 짧은 시간에 앱 화면을 보는 경험 만으로는 평가가 어려움)
-   어떻게 서비스를 테스트 할 것인가에 대한 고려가 필요함. 외국인 대상의 서비스면 외국인 대상으로, 아동 대상의 서비스면 아동 대상으로 테스트 해야하므로, 테스트를 위하여 60명 이상의 평가 인원 참여가(A테스트 30명, B테스트 30명) 가능한 주제를 선택함. 평가 참여 인원은 많을수록 좋음.

(문헌22) 통합 데이터지도-공공 민간 빅데이터 통합검색 https://www.bigdata-map.or

(문헌23) MDIS 마이크로데이터 통합서비스 https://mdis.kostat.go.kr

(문헌24) 서울 열린데이터광장 https://data.seoul.go.kr
