# ch2. 데이터 큐레이션과 EDA, 디자인 인사이트

## 데이터 큐레이션의 여러 방법들

데이터 큐레이션(Data Curation)이란 프로젝트에 필요한 데이터를 선정하고 수집하거나 생성하는 데이터 관리의 과정을 통하여 데이터의 가치를 높이는 행위를 말합니다.(25) 즉, 우리가 분석하고, 이해하고자 하는 대상인 데이터를 확보하는 행위인데요, 데이터 확보의 방법은 기존에 존재하는 데이터를 찾아서 수집하는 방법과 기존에 없던 데이터를 생성하는 두 가지 방법이 있고, 프로젝트의 성격에 따라 두 방법 중에 적절한 방법을 선택하거나 두 방법을 동시에 사용하기도 합니다.

## 1) 기존의 데이터를 수집하여 큐레이션하는 경우

예를 들어 기존의 서비스에 대한 설문 조사, 시장 자료, 웹/앱 서비스 로그 기록, SNS 데이터, IoT 센서 데이터 등이 존재한다면, 이들을 수집할 수 있고, 이미 수집되어 있는 데이터의 확보가 가능하다면 가장 편리한 데이터 큐레이션 방법이겠으나, 많은 경우 원하는 데이터가 내 필요에 맞게 정리되어 있는 경우는 없습니다. 그러므로 내 필요에 적합한 데이터가 가공된 형태로 존재하지 않아도, 여러 관련 데이터를 수집하고 이들을 가공하여 필요한 형태로 재구성하는 경우가 더 많습니다. 또 웹이나 앱 형태의 디지털 서비스들은 서비스 관련 데이터를 실시간으로 확인하거나, 지속적으로 데이터를 축적하고 특정 변수를 모니터하는 것이 가능합니다. 이런 경우는 서비스를 모니터링하기 적합한 데이터 대시보드를 구성해놓고, 관찰 주기나 필요 시점에 따라 바로 데이터 상황을 확인할 수 있는 장점이 있고, 대부분의 상용화된 디지털 서비스는 이러한 데이터 모니터링 시스템을 갖추고 있습니다. 데이터 모니터링 시스템이 있는 경우에는 데이터 분석과 디자인 테스팅을 매우 효과적으로 반복 수행할 수 있습니다. 린 UX를 적용하기 좋은 환경인 것이죠.

이미 수집된 데이터를 찾을 때 다양한 검색 옵션으로 데이터 셋을 찾아볼 수 있는 구글 데이터셋 검색 서비스도 활용해보기 바랍니다.

-   구글 데이터셋 검색 (26)

[Dataset Search](https://datasetsearch.research.google.com)

## 2) 데이터를 새로 생성하여 큐레이션 하는 경우

분석에 필요한 데이터가 없는 경우에는 직접 설문 조사나 사용성 테스트, 시장 분석, 센서 설치 등을 수행하여 필요한 데이터들을 확보합니다. 새로운 프로젝트나 실험을 하는 경우에는 보통 데이터 생성 방법을 통하여 데이터 분석을 실시합니다. 새로 데이터를 생성하는 경우는 프로젝트에 필요한 형식과 내용을 맞추어 데이터를 확보할 수 있는 이상적인 방법이지만 데이터를 생성하는데, 시간과 노력이 많이 요구될 수 있습니다. 특히 장기간, 다량의 데이터를 확보하기 위해서는 많은 자원이 필요하므로, 프로젝트의 여건을 잘 고려하여 데이터 생성 계획을 추진해야 합니다.

최근에는 생성형 인공지능을 사용하여 사용자나 사용 상황에 대한 테스트 데이터를 생성하고, 이 데이터로 출시되지 않은 서비스나 기능을 실험할 수도 있습니다. 다만 인공지능이 생성한 데이터는 가상의 데이터이므로 인공지능 서비스의 성능과 한계를 잘 이해하여 활용해야 합니다.

## 탐구적 데이터 분석(EDA)의 과정과 방법

이제는 데이터 큐레이션으로 확보한 데이터들을 탐구적 데이터 분석으로 이해할 차례인데요, 앞서의 이론 학습에서 탐구적 데이터 분석은 데이터 시각화 기술을 사용하여 데이터의 특징을 탐지하고 트렌드나 패턴을 확인하여 인사이트를 발견하는 데이터 분석 방법으로 설명했었습니다. 그리고 탐구적 데이터 분석 과정의 특징인 단계적이고 반복적인 수행 과정이 디자인 리서치 과정과 유사하다고 했지요. 이번에는 탐구적 데이터 분석 과정을 단위 행동으로 나누어 실습해보도록 하겠습니다. 아래의 설명들은 데이터 문해력이 갖춰진 경우에는 이해하기 쉽겠으나, 그렇지 않은 경우에는 개념이 어려울 수 있습니다. 원본 데이터를 수집하여 탐구적 데이터 분석을 실시하는 경우에는 아래의 과정들이 모두 필요합니다. 그러나 이미 분석된 그래프나 보고서를 사용하는 경우에는 탐구적 데이터 분석 과정을 참고하여 어떤 시각에서 필요한 디자인 인사이트를 발견할 수 있는지를 이해하고 적용하면 됩니다.

## 1) 데이터 구조와 변수의 이해

데이터 구조와 변수를 이해하기 위해 먼저, 확보한 데이터 셋의 형식을 확인하고, 분석에 편리한 형식으로 전환하거나 가공할 필요가 있습니다. csv, xlsx, json 등 다양한 형식의 데이터가 있고, 데이터 분석도구에 따라 적합한 파일 형식이 있으므로 파일 형식을 확인하고, 필요한 파일 형식으로 변환합니다. 그리고 데이터의 구조와 변수, 값의 형식을 확인합니다. 어떤 변수들이 수집되어 있는지, 변수의 값은 어떤 형식인지(정수, 실수, 문자, 범주, 논리, 시간 값 등)를 확인하고, 분석 용도에 맞게 값의 형식을 정리합니다. 변수 값의 형식에 따라 분석할 수 있는 내용이 달라지므로 데이터 형식의 가공은 매우 중요한 과정입니다. 또 변수들을 통합하거나 값에 따라 변수를 분리하는 작업이 필요할 수 있습니다. 여러 데이터 파일들을 공통 변수를 기준으로 통합하면 새로운 변수 간의 관계를 발견할 수 있습니다. 데이터에서 필요없는 변수를 삭제하고, 가독성을 위해 변수 명을 정리하거나 결측값의 처리 방법을 결정하여 정리하는 것도 효율적인 데이터 분석을 하기 위해 필요한 전처리 과정입니다.

예를들어 앞선 사례의 서울시 미세먼지 측정 데이터는 한 변수로 되어있는 미세먼지 측정값과 초미세먼지 측정값을 두 개의 독립된 변수로 분리하는 작업이 필요했고, 측정소 번호는 숫자가 아닌 문자 형식으로 변환하여 측정소 별로 데이터를 분석할 수 있게 했습니다. 또 미세먼지 측정값과 날씨의 관계를 알기 위하여 분리되어 있던 날씨 데이터와 미세먼지 측정 데이터를 측정 시간을 기준으로 결합하는 작업을 했습니다. 이러한 전처리 작업은 이후의 데이터 분석 작업의 효율을 높이고, 사용 목적에 맞는 데이터 분석을 가능하게 합니다.

## 2) 변수 별 현황값의 이해 (기술 통계: Descriptive Statistics)

데이터 가공과 전처리가 완료되었으면, 데이터의 각 변수 별로 값이 어떻게 표현 되는지를 분석합니다. 미세먼지 측정 데이터를 예로 들면, 미세먼지, 초미세먼지의 측정 현황이 어떻게 되는지를 관찰하는 작업입니다. 측정값은 시간이나 측정 장소의 구분에 따라 최소값, 최대값, 평균값, 중간값 등 데이터의 상태를 보여주는 대표값들이 나올 수 있습니다. 또 시간이나 장소의 구분에 따라 값이 어떻게 변화하는지, 평균과 각 값은 얼마나 차이가 나는지를 조사할 수 있습니다. 이렇게 변수 별 현황값의 이해 단계에서는 변수 별로 대표 값과 값의 변동 현황을 조사합니다. 그리고 기술 통계값에서 디자인에 필요한 정보가 발견되면 디자인 인사이트의 목록으로 수집합니다. 예를들어, 미세먼지 측정값의 범위를 알면 서비스에서 사용할 측정 단위와 단위 표현 간격 등을 결정할 수 있습니다. 기술 통계값은 값 자체를 디자인 인사이트로 직접 사용할 수도 있지만, 대표값의 현황으로 부터 다음 단계에서 어떤 시각화 분석이 필요한지와 그래프 표현 방법을 결정하는 단서로도 사용됩니다.

## 3) 변수의 시각화, 변수 간 시각화를 통한 데이터 변동과 패턴 이해

이제는 데이터 현황을 그래프를 통하여 시각적으로 확인해볼 차례입니다. 먼저 앞 단계에서 기술 통계로 알아본 각 변수의 내용을 그래프로 시각화하여 현황을 조사합니다. 데이터 시각화를 통하여 대표값 만으로는 발견하기 어려운 변수값의 변화 추세와 패턴을 직관적으로 알 수 있습니다. 어떤 기준(X축에 표기)에 의하여 값(Y축에 표기)은 비례하여 증가하거나, 감소하거나, 또는 기준 값의 변화와 관련 없을 수 있으며, 범위나 분포의 패턴을 관찰할 수도 있습니다. 이러한 변수 값의 시각화는 표현 기준을 달리 함으로써 다면적으로 변수 값을 이해하게 합니다.

각 변수 별로 시각화를 수행했다면, 이번에는 데이터 셋의 두 변수를 선택하여 관계를 볼 수 있는 그래프를 제작하여 변수 간의 관계를 관찰합니다. 변수 간의 관계는 인과 관계, 상관 관계 등으로 표현됩니다. 예를들어 미세먼지 측정량이 많아지면, 초미세먼지 측정량도 많아지는 지를 그래프로 그려서 조사해볼 수 있습니다. 앞서 사례 연구에서 두 측정량은 전반적으로는 비례 관계에 있지만 비례의 강도는 지역이나 관측 시기에 따라서 다른 것으로 조사되었습니다. 변수 간 시각화를 진행할 때는 기술 통계값이나 각 변수의 시각화 그래프를 바탕으로 논리적인 질문들을 제시해가며, 하나씩 답을 확인해보는 방법으로 수행합니다. 이 과정에서 좋은 디자인 인사이트가 많이 발견될 수 있습니다. 데이터 시각화를 통하여 값의 변동 추세, 값의 관계를 발견하는 활동은 탐구적 데이터 분석 방법론의 핵심 활동이므로, 충분한 시간을 가지고 다면적인 시각화와 해석을 여러 번 진행하기를 권합니다. 앞서 소개한 BI(Business Intelignece) 서비스들을 활용하면, 기본적인 데이터 시각화를 쉽게, 또는 자동적으로 수행할 수 있습니다. 최근의 서비스들은 인공지능 기술을 도입해서 해석도 자동으로 생성해줍니다. 하지만 제안된 해석을 그대로 사용할 지, 다른 관점을 반영하여 재해석 할지는 디자이너의 몫이므로 제안 내용을 잘 판단하고, 데이터 분석 과정을 관리할 수 있는 역량을 가지고 BI 서비스를 사용해야합니다.

## 실습과제 3: 데이터 큐레이션과 EDA

실습 과제 2에서 타겟 서비스(A 디자인)를 결정한 상태이므로, 이제는 좀 더 구체적인 데이터 큐레이션과 탐구적 데이터 분석을 시행해보겠습니다.

-   먼저, 타겟 서비스가 정해졌으니, 우리의 실습 과제를 명확하게 정의하는 프로젝트 선언문(Project Statement)을 작성합니다. 실습 과제의 내용을 한 문장으로 요약한 프로젝트 선언문에는 서비스의 사용자가 누구이며, 어떤 사용 상황에 있는지, 서비스의 주요 내용과 가치는 무엇인지를 문장으로 구성합니다. 본 과제의 특징을 반영하여 다음의 문장 요소를 템플릿으로 사용하여 작성해도 됩니다.
    -   Project Statement: (리서치한 데이터 내용의) 데이터 인사이트를 기반으로 (Target Service) 앱의 (사용자 경험A), (사용자 경험B) 에 대한 개선 디자인을 제안한다. (+ 제안한 디자인은 A/B 테스트를 통하여 앱 서비스의 개선 여부를 검증한다.)
-   데이터 큐레이션: 기존의 데이터를 검색, 수집하는 방법으로 데이터 큐레이션을 실시합니다. 타겟 서비스를 선정할 때 분석한 데이터에 더하여, 타겟 서비스의 사용자와 사용 상황, 서비스 내용을 특정하여 더 많은 관련 데이터를 수집합니다. 되도록 타겟 서비스와 직접적으로 관련된 데이터를 수집하는 것이 좋고, 데이터의 수집 시점, 수집 사례 수, 데이터의 신뢰성, 분석에 적합한 형식 여부 등을 고려하여 데이터를 확보합니다. 수집한 데이터의 출처와 형식 정보를 함께 기술합니다.
-   탐구적 데이터 분석: 이론에서 설명한 탐구적 데이터 분석 기법을 적용하여 수집된 데이터들을 분석하고 인사이트를 도출합니다. 데이터의 구조, 변수의 대표값, 변수의 변동 패턴과 관계 패턴이라는 여러 가지 관점에서 단계적으로 데이터를 분석하고 데이터의 의미를 발견합니다. 이렇게 하여 발견한 데이터 인사이트들을 목록화 합니다. 인사이트를 얼마나 많이 도출하는 것이 적절한지는 과제와 데이터의 특징에 따라 다르겠으나, 적어도 30개 이상의 목록을 권합니다. 다음 단계에서 디자인 문제의 구조를 구성하기 위해서는 섬세하고, 다양한 관점의 인사이트가 많을수록 좋습니다. 데이터의 인사이트를 작성할 때는 사용자, 사용 상황, 서비스 내용과 연계하여 문장을 서술합니다.

지금까지 작업한 프로젝트 선언문, 데이터 큐레이션, 탐구적 데이터 분석과 디자인 인사이트 수집을 실시하여 발표자료 형식으로 정리하여 문서화 합니다.

## 실습과제 3 Check Point!

데이터 큐레이션과 탐구적 데이터 분석 활동에서 아래의 내용을 고려하여 진행하기 바랍니다.

-   서비스 필요성을 설명하는 데이터에 집착하지 말것. 서비스의 필요성은 이미 전제되어 있으므로 필요성 보다는 서비스의 현황을 이해할 수 있는 데이터를 수집해야함.
-   데이터 신뢰성 확보를 위하여 출처 서술 필요함.
-   데이터 분석(리서치) 활동들의 연계성, 인과관계가 중요함.
-   수집한 데이터들에 대하여 왜 이 데이터가 필요한지, 데이터를 어떻게 분석 했는지, 그래서 무엇을 알았는지, 알게된 것은 어떻게 인사이트로 적용하는지가 공감되도록 분석 보고서를 작성함.

## 실습과제 4: 타겟 서비스(A 디자인) 현황 분석

실습과제 3이 타겟 서비스와 관련한 광범위한 데이터 수집과 붆석을 목표로 진행했다면, 실습과제 4는 타겟 서비스의 디자인 현황을 분석하는데 집중합니다. 타겟 서비스는 이미 운영되고 있는 서비스이므로 서비스의 기존 디자인이 존재합니다. 이 디자인에는 콘텐츠와 네비게이션 구조, 제공 서비스(기능), 사용 경로, 화면의 그래픽 요소 및 GUI 디자인, 화면 및 구성 요소들의 인터렉션, 콘텐츠 원고의 작성 스타일 등 여러가지 사용자 경험들이 포함되어 있습니다.

-   먼저 여러분이 사용자라고 가정하고, 타겟 앱 서비스가 제공하는 사용자 경험을 사용 경로를 따라 검토해보며 인사이트를 발견하세요. 그리고 서비스의 화면 별로도 사용자 경험을 분석하여 인사이트를 도출합니다. 앱 서비스의 경우 앱을 열고 가장 먼저 만나는 홈 화면, 그리고 가장 자주 사용하게 될 서비스의 주요 화면에 특히 집중하여 사용자 경험을 검토합니다. 우리는 모든 디자인 문제를 완벽하게 해결하려는 것이 아니라 중요한 서비스 목표를 달성하기 위한 디자인을 할 것이므로, 많은 사용자가 자주 접하는 사용자 경험을 자세히 분석하는 것이 중요합니다.
-   타겟 앱 분석은 버튼이나 콘텐츠 레이블(Label) 같이 페이지를 구성하는 단위 구성요소별로 분석하지 않고, 예를들어 ‘검색 키워드 제안 받기’와 같은 사용자 경험의 행동 단위를 따라 분석합니다. 즉 ‘방문한 장소 검색 화면에서(경로/화면) 제시된 검색 키워드를 사용할 때(단위 사용자 경험) 제안 키워드를 수정할 수 없다.’(형용사적/동사적 서술)와 같이 인사이트를 서술합니다. 만약 디자이너 본인이 타겟 앱의 사용자와 매우 다른 퍼소나(Persona)의 사용자라면, 적절한 퍼소나를 설정하여 해당 퍼소나의 사용 상황을 가정하고 분석하는 것이 좋습니다. 예를들어 게임을 좋아하는 10대 사용자의 퍼소나를 써야한다면 해당 사용자의 특징을 반영하여 사용자 경험을 검토해야합니다. 실무적으로는 퍼소나에 맞는 실제 사용자를 대상으로 관찰하는 것이 이상적이지만, 과제 여건에 따라 어려운 경우도 있으므로, 이런 경우에는 실습과제 3의 사용자 데이터 수집 비중을 높여서 진행합니다.
-   타겟 서비스 현황 분석의 결과는 타겟 서비스의 진행 경로와 화면 구성을 잘 이해할 수 있도록 시각적 이미지로 현황을 보여주고, 이미지에 인사이트의 해당 부분을 표기하여 문제의 이해도를 높여줍니다. 콘텐츠 규모가 크거나, 기능이 많은 경우, 다양한 니즈의 여러 사용자가 존재하는 경우에는 현황 분석에 더 많은 시간과 노력이 필요합니다. 충분한 시간을 들여서 자세히 사용자 경험들을 검토하기 바랍니다.

이상의 내용을 고려하여 타겟 서비스의 사용자 경험을 분석하고 인사이트를 모아 목록을 작성합니다. 과제에서 수행한 내용은 문서화하여 소통합니다.

다음 단계에서는 실습과제 3, 4를 통하여 얻은 프로젝트의 디자인 인사이트 목록을 사용하여 문제의 구조를 도출하고, 문제의 구조를 바탕으로 KPI를 설정하도록 하겠습니다.

## 데이터 큐레이션, 탐구적 데이터 분석, 타겟 서비스 분석에서 AI의 활용

디자인 리서치 과정에서 인공지능 서비스를 잘 사용하면 작업의 난이도와 효율을 높일 수 있습니다. 인공지능 서비스는 하루가 다르게 발전하고, 새로운 방식이 도입되고 있기 때문에 특정 방법이나 과정을 안내하기는 어렵지만, 실습과제를 수행하면서 인공지능에게 어떤 요청을 하고, 어떤 결과물을 받으면 좋을지를 정리해보겠습니다.

-   데이터 큐레이션: 디자인 리서치에 적합한 기존의 데이터를 찾거나 추천하는 것은 인공지능이 잘 할 수 있는 업무는 아닙니다. 생성형 인공지능은 환각 현상 문제와 이미 학습된 데이터를 기반으로 응답하는 문제가 있어서 최신이면서도 정확한 정보를 AI 서비스로 찾아내는 데는 아직 한계가 있을 수 있습니다. 대신, 데이터를 검색할 때 어떤 데이터 서비스에서 어떻게 검색 조건을 쓰면 원하는 데이터를 찾을 수 있는지를 판단하는 데에 활용하는 것이 현실적이라고 봅니다.

    한편, 생성형 AI의 특징은 테스트 데이터를 생성하는 데는 강점이 될 수 있습니다. 원하는 조건의 퍼소나(persona) 데이터나 사용 시나리오를 다수 생성하거나, 데이터의 형태(변수와 값, 관측 수)를 정의하고 이에 맞게 테스트 데이터를 생성하는 일은 편리하게 수행할 수 있으므로, 이를 이용하여 데이터를 기획하고, 데이터 형식을 검증하는 일에는 적합합니다. 이 경우에도 인공지능이 생성한 데이터는 현실 데이터가 아니므로, 데이터의 값을 신뢰할 수는 없습니다.

-   탐구적 데이터 분석: 데이터를 가공하거나 분석하고, 그래프로 시각화하거나, 데이터의 인사이트를 요약하는 것은 인공지능이 잘 하는 일입니다. 데이터 분석을 수행하는 인공지능 서비스도 많이 나와 있구요. 어떤 서비스는 데이터만 제공하면 주요 내용에 대한 분석 보고서를 생성해주기도 합니다. 또 2-4에서 소개한 BI 서비스들은 비즈니스에서 반복적으로 수집되고, 축적되는 데이터들을 지속적으로 모니터링하고, 문제 상황을 감지하거나 예측할 수도 있습니다. 그러므로 본인의 업무 상황과 필요에 적합한 AI 서비스를 선택한다면, 탐구적 데이터 분석 과정은 비교적 쉽게 진행됩니다. 다만, 탐구적 데이터 분석을 잘 하려면, 디자이너가 필요한 정보와 분석 방법을 요청하고, 분석 과정을 관리하고, 결과를 검수 할 수 있는 데이터 문해력과 분석 도구의 사용 능력을 함께 갖춰야합니다. 데이터 분석 전문가인 인공지능과 소통하고, 협업 과정을 이끌 수 있는 역량이 필요하다는 것입니다.

-   타겟 서비스의 디자인 현황 분석: 최근의 인공지능 서비스들은 디자인 화면을 제시하면, 유사한 디자인 사례를 검색해주거나, 화면의 디자인 구성 요소들을 추출하거나, 사용자의 워크플로우를 제안해주는 등, 디자이너의 수고를 덜어주는 서비스들이 다수 나와 있습니다. 이렇게 분석 작업의 과정을 지원하는 인공지능 서비스들은 당연히 잘 사용하는 것이 좋겠고, 타겟 서비스의 디자인 장점과 문제점을 분석 표나 보고서 원고 형태로 생성할 수 있습니다. 이 경우에는 표나 보고서의 구체적인 형식과 내용 예시 등을 템플릿으로 제시하여 원하는 내용으로 결과가 정리되도록 합니다. 이번 연습 과제에는 포함되지 않지만, 사용자 테스트를 기획하거나, 사용자 테스트 결과 데이터를 분석하는 방법을 실험해보는 일에도 인공지능을 활용하는 것이 편리합니다.

(문헌25) Renee. Miller, “Big Data Curation”, 20th International Conference on Management of Data (COMAD), (2014), p.4

(문헌26) Google Dataset Search, <https://datasetsearch.research.google.com>
