# References {.unnumbered}

::: {#refs}
:::

## Part 1. UX 디자인과 데이터

**ch1. UX 디자인의 오늘과 변화의 방향**

(문헌1) Yvonne Rogers, Helen Sharp, Jennifer Preece, 『Interaction Design: Beyond Human-Computer Interaction 6th edition』, Wiley. Kindle Edition, (2023)

(문헌2) Kate Moran, Sarah Gibbons, “Generative UI and Outcome-Oriented Design”, [https://www.nngroup.com/articles/generative-ui/](https://www.nngroup.com/articles/generative-ui/), (2024)

**ch2. UX 디자인과 데이터, AI**

(문헌 3) Spotify(스포티파이), Apple app store

(문헌 4) Kate Moran, Jakob Nielsen, “AI for UX: Getting Started”, [https://www.nngroup.com/articles/ai-ux-getting-started/](https://www.nngroup.com/articles/ai-ux-getting-started/), (2023)

(문헌 5) Figma Learn, “Config 2024에서 발표된 새로운 기능”, [https://help.figma.com/hc/ko/articles/24037640924823-Config-2024에서-발표된-새로운-기능](https://help.figma.com/hc/ko/articles/24037640924823-Config-2024%EC%97%90%EC%84%9C-%EB%B0%9C%ED%91%9C%EB%90%9C-%EC%83%88%EB%A1%9C%EC%9A%B4-%EA%B8%B0%EB%8A%A5), (2024)

**ch3. 데이터 기반 디자인 (Data Driven Design)**

(문헌 3) Spotify(스포티파이), Apple app store

(문헌 4) Kate Moran, Jakob Nielsen, “AI for UX: Getting Started”, [https://www.nngroup.com/articles/ai-ux-getting-started/](https://www.nngroup.com/articles/ai-ux-getting-started/), (2023)

(문헌 5) Figma Learn, “Config 2024에서 발표된 새로운 기능”, [https://help.figma.com/hc/ko/articles/24037640924823-Config-2024에서-발표된-새로운-기능](https://help.figma.com/hc/ko/articles/24037640924823-Config-2024%EC%97%90%EC%84%9C-%EB%B0%9C%ED%91%9C%EB%90%9C-%EC%83%88%EB%A1%9C%EC%9A%B4-%EA%B8%B0%EB%8A%A5), (2024)

## Part 2. 디자인 리서치를 위한 탐구적 데이터 분석

**ch1. 디자인 리서치와 탐구적 데이터 분석 (EDA: Exploratory Data Analysis)**

(문헌 9) Hadley Wichham, Garrett. Grolemund, 『R for Data Science(2e.)』, (2023), [https://r4ds.hadley.nz/intro](https://r4ds.hadley.nz/intro)

**ch2. 디자인 리서치를 위한 탐구적 데이터 분석 사례 (1): 서울시 미세먼지 측정 데이터 분석 사례**

(문헌 7) 이현진, 『데이터 드리븐 디자인』, UX리뷰, (2024), pp.100-143

**ch3. 디자인 리서치를 위한 탐구적 데이터 분석 사례 (2): StudentLife 데이터 분석 사례**

(문헌 10) Dartmouth College, “StudentLife Study”, (2024.7.24), [https://studentlife.cs.dartmouth.edu](https://studentlife.cs.dartmouth.edu/)

(문헌 11) Kaggle, “College Experience Study Dataset”, (2024.7.31) [https://www.kaggle.com/datasets/subigyanepal/college-experience-dataset?resource=download](https://www.kaggle.com/datasets/subigyanepal/college-experience-dataset?resource=download)

(문헌 12) Rui Wang, et al., ”SmartGPA: How Smartphones Can Assess and Predict Academic Performance of College Students”, UbiComp ’15, September 07-11, 2015, Osaka, Japan

(문헌 13) R. Wang et. al., “Tracking Depression Dynamics in College Students Using MobilePhone and Wearable Sensing”, Proceedings of the ACM on Interactive, Mobile, Wearable and Ubiquitous Technologies, Vol. 2, No. 1, Article 43. (2018).

(문헌 14) D. L Mack, et al., “Mental Health and Behavior of College Students During the COVID-19 Pandemic: Longitudinal Mobile Smartphone and Ecological Momentary Assessment Study, Part II”, JOURNAL OF MEDICAL INTERNET RESEARCH, vol. 23, iss. 6, e28892 (2021)

(문헌 15) Subigya Nepal, et al. “Capturing the College Experience: A Four-Year Mobile Sensing Study of Mental Health, Resilience and Behavior of College Students during the Pandemic.” Proceedings of the ACM on Interactive, Mobile, Wearable and Ubiquitous Technologies. (2024)

**ch4. EDA를 위한 데이터 분석 도구들**

(문헌 16) Google marketing platform, “애널리틱스 기능” [https://marketingplatform.google.com/intl/ko/about/analytics/features/](https://marketingplatform.google.com/intl/ko/about/analytics/features/)

(문헌 17) Microsoft, “Power BI 둘러보기” [https://powerbi.microsoft.com/ko-kr/guidedtour/power-platform/power-bi/2/1](https://powerbi.microsoft.com/ko-kr/guidedtour/power-platform/power-bi/2/1)

(문헌 18) Tableau, “Tableau product” [https://www.tableau.com/ko-kr/products/tableau](https://www.tableau.com/ko-kr/products/tableau)

(문헌 19) Beausable, “Why Beausable”, [https://www.beusable.net/ko/](https://www.beusable.net/ko/)

**ch5. Lean UX 프로세스와 데이터 기반 디자인**

(문헌 20) 로라 클라인, (김수영, 박기석 역), 『린 스타트업 실전 UX』, 한빛미디어,(2014)

(문헌 21) Google Developers, “UXD: What is Lean UX?”, [https://www.youtube.com/watch?v=7NkMm5WefBA](https://www.youtube.com/watch?v=7NkMm5WefBA), (2023)

## Part 3. 기존 디자인(A 디자인) 리서치와 개선 디자인(B 디자인) 제안

**ch1. 실습과제의 디자인 프로세스, 주제 선정**

(문헌 22) 통합 데이터지도-공공 민간 빅데이터 통합검색 [https://www.bigdata-map.or](https://www.bigdata-map.or)

(문헌 23) MDIS 마이크로데이터 통합서비스 [https://mdis.kostat.go.kr](https://mdis.kostat.go.kr)

(문헌 24) 서울 열린데이터광장 [https://data.seoul.go.kr](https://data.seoul.go.kr)

**ch2. 데이터 큐레이션과 EDA, 디자인 인사이트**

(문헌 25) Renee. Miller, “Big Data Curation”, 20th International Conference on Management of Data (COMAD), (2014), p.4

(문헌 26) Google Dataset Search, [https://datasetsearch.research.google.com](https://datasetsearch.research.google.com)

**ch4. Design Concept & MVP (Minimum Viable Product) Design**

(문헌 27) Aaron Gitlin, “Becoming a data-aware designer”, [https://uxdesign.cc/becoming-a-data-aware-designer-1d7614ebc3ed](https://uxdesign.cc/becoming-a-data-aware-designer-1d7614ebc3ed)

(문헌 28) Paperless Post, “online invitations for all moments that matter”, [https://www.paperlesspost.com](https://www.paperlesspost.com)

## Part 4. 개선 디자인의 검증: A/B Testing

**ch1. A/B 테스팅을 위한 기초 통계와 가설 검증 기법**

(문헌 20) 로라 클라인, (김수영, 박기석 역), 『린 스타트업 실전 UX』, 한빛미디어,(2014)

**ch2. F-test와 T-test의 실습 방법들**

(문헌 29) 구글Docs 편집기 고객센터, “FTEST”, [https://support.google.com/docs/answer/7004183?hl=ko&ref_topic=3105600](https://support.google.com/docs/answer/7004183?hl=ko&ref_topic=3105600)

(문헌 30) 구글Docs 편집기 고객센터, “TTEST”, [https://support.google.com/docs/answer/6055837?hl=ko](https://support.google.com
