project:
  type: book
  output-dir: docs

lang: ko-KR


book:
  title: 데이터 기반 디자인과 A/B 테스팅
  chapters:
    - index.qmd


  cover-image: hexlogo/bitPublish_logo.png    
bibliography: references.bib
link-citations: false
keep-tex: false
citation_package: biblatex
biblatexoptions: [backend=biber,nohashothers=true, maxcitenames =2,bibstyle=authoryear,citestyle=authoryear]
            