# ch3. 실습 과제의 A/B 테스팅 기획

이제는 이번 단원에서 공부한 A/B 테스팅 방법론을 바탕으로 우리가 진행한 실습과제의 A디자인과 B디자인의 KPI가 차이가 있는지를 실험해보겠습니다.

우리 실습과제 프로젝트의 특징은 A/B 테스팅을 설문의 방법으로 한다는 것입니다. 그 이유는 우리가 실제 서비스 로그 데이터에 접근하기 어렵기 때문이라고 했었죠. 로그 데이터가 사용자의 행동을 그대로 반영하는 반면, 설문은 사용자가 의식적으로 답을 생각해내는 것이므로, 실제 행동 내용과는 다른 주관성의 개입 여지가 있습니다. 그래서 설문으로 A/B 테스팅을 하는 경우는 서비스 로그 데이터를 사용하는 방법에 비하여 아래와 같이 몇가지 고려할 점이 더 있습니다.

### 설문을 통한 A/B 테스트를 기획할 때 유의할 점

-   적절한 샘플 크기와 설문 문항수: 충분한 데이터 수집을 위해 설문 응답자가 많아야 합니다. 최소 30명 이상의 응답자가 필요합니다. 우리 실험에서는 A 디자인에 대한 응답자 30명 이상, B디자인에 대한 응답자 30명 이상이 필요합니다. 두 그룹의 응답자 인원이 똑같지는 않아도 됩니다. 다만 너무 응답자 차이가 많이 나면 정규성과 분산 차이가 있을 수 있으므로, 비슷한 수준에서 결정합니다. 문항 수는 너무 많으면 응답자 피로가 발생하므로, 핵심 질문에 집중해 10\~15문항 정도가 적절합니다. 우리 실험에서는 되도록 10개 문항 이하로 합니다.
-   설문 질문 작성 시 고려할 점:
    -   명확성: 질문이 이해하기 쉽고 명확해야 하며, 이중 부정문을 피합니다. 설문 대상자에게 적합한 용어와 서술 방법을 사용하고, 설문 대상자는 사용자이지, 전문가가 아니므로 디자인이나 기술 관련 기술 용어들을 쓰는 것을 지양합니다.
    -   중립적 표현: 편향된 질문이나 응답을 유도하는 표현을 피합니다. 특히 A,B 디자인에서 한 쪽 디자인에만 유리한 질문은 피합니다.
    -   순서 효과 고려: 설문 응답자는 질문 순서에 큰 영향을 받습니다. 쉬운 질문부터 진행하고, 질문 순서가 논리적으로 구성되도록하여 질문 순서가 응답에 미치는 영향을 최소화합니다.
    -   두 그룹의 설문 내용은 A, B 디자인의 내용만 제외하고 원고와 순서, 표현 및 응답 방법이 모두 동일해야합니다.
-   설문 데이터 분포의 불확실성 반영: 설문은 사용자의 행동보다는 의도가 반영되기 때문에, 응답 분포가 넓어집니다. 그러므로 문항 설계에서 Likert 5점 척도보다 7점 척도를 사용하는 것이 좋습니다. 7점 척도가 응답자들이 미세한 차이를 표현할 수 있어 데이터 분포가 더 세밀하게 나타나기 때문입니다. 그리고 중립적인 선택지를 추가해 응답자의 의견이 극단으로 치우치지 않도록 합니다. 또한 각 척도의 항목이 명확하고 일관성 있게 작성되어야 합니다. 이 내용은 설문 기법 이론으로도 나와 있지만, 수년 간 A/B 테스팅을 실험해본 결과, 7점 척도의 응답이 더 명확하게 차이를 드러내는 것을 경험했습니다.
-   설문 결과의 p-value 해석: p-value가 크게 나오는 경우, 데이터가 충분하지 않거나 분산이 클 수 있습니다. 이 경우 90% 신뢰구간(유의수준 0.1)으로 해석해 보는 것도 하나의 방법입니다. 이는 더 관대한 기준을 적용해 유의미한 차이를 발견할 수 있도록 합니다. 이 부분은 해당 실습과제에서 더 자세히 설명하도록 하겠습니다.
-   설문 의견과 사용자 행동 간 차이 인정: 설문 데이터는 실제 사용자 행동과 다를 수 있습니다. 따라서 설문 결과가 실제로 행동으로 이어질 가능성을 고려하고, 필요시 추가적인 행동 데이터 분석을 통해 설문 결과를 보완합니다. 사용자 설문의 의견은 분포 범위가 넓고 불분명할 수 있으므로, 데이터 분석 시 분산이나 변동성을 주의 깊게 살펴봐야 합니다. 이는 결과의 신뢰도를 높이는 데 중요합니다. 보통 설문 응답이어서 보정이 필요한 문제는 테스트 후 의사결정 단계에서 반영합니다. 어떤 후속 조치를 할지, 디자인 수정을 어떻게 해야할지를 결정할 때 고려할 요인입니다.

### 실습과제 9: A/B 테스팅을 위한 설문 기획

다음의 항목에 따라 A/B 테스팅을 위한 설문 기획서를 작성합니다.

1.  평가 목적: 프로젝트에서 A/B테스트할 항목(KPI)을 3개 이상 서술하고, 테스트 항목 별로 질문 또는 관찰할 내용을 각 KPI 당 2개 이상 제시합니다. 실습과제 6에서 도출한 KPI를 반영합니다.

2.  평가 내용 1 : 각 테스트 항목 마다 필요한 디자인 화면 (A화면, B화면)및 질문 원고, 응답 형식을 제시합니다. 제시하는 화면은 기존의 A 디자인, 개선한 B 디자인의 화면은 동일한 상황과 사용자 목표에 대응하도록 기획하며, 설문에서 제시하는 화면의 수, 제시 순서, 제시 방법까지 모두 동일하게 맞춰줍니다.

    질문의 응답 형식은 Likert 7점 척도를 사용합니다. 질문 내용은 KPI 지표로 사용할 수 있는 내용이어야 합니다. 보통 KPI와 연계된 사용 의도, 만족도, 이해도, 선호도 등을 측정할 수 있는 질문이 사용됩니다.

3.  평가 내용 2: A/B 테스트와는 상관없지만, 디자인 개선에 도움이 될 만한 추가 질문 원고를 작성합니다. 각 질문에서 무엇을 알고자 하는지를 정의하고, 이에 맞게 원고를 작성합니다. 정량/ 정성적 질문 모두 가능하며, 주관식 질문도 괜찮습니다. 이 질문들의 응답 내용은 A/B 테스트의 결과를 이해하거나 보강하는 데 사용됩니다. 단 주관식 질문은 너무 어렵지 않게 하고, 열린 응답을 하도록 하며, 전체 설문 순서에서 뒤쪽이나, 마지막 순서에 배정합니다. 보통 주관식 질문은 답하지 않는 응답자도 많으므로, 가장 중요한 질문을 주관식으로 기획하면 안됩니다.

4.  테스트 형식은 구글 설문지 양식을 사용하여 두 비교 그룹에 대하여 각 30명 이상 설문 진행 예정이고, 설문 대상자에게 온라인으로 설문 링크를 제공하는 형식으로 합니다. 설문 대상자 대다수가 모바일 폰으로 설문 응답을 하게 되므로 폰 레이아웃에서 설문지 디자인이 의도대로 보이는지 확인해야합니다. A 디자인 설문지, B 디자인 설문지가 게시된 모바일 폰 화면을 나란히 놓고, 서로 비교하여 문제 부분이 있는지, 검수합니다.

    ![\[그림 40\] 커뮤니티 기반 산책 앱의 기존 디자인(A안)과 개선 디자인(B안)의 비교 화면과 설문 문항 예시](ch3 실습 과제의 A B 테스팅 기획/40.png)

### A/B 테스팅을 위한 설문 기획 Check Point!

-   A안과 B안의 조사 대상 페이지 수와 콘텐츠(텍스트 원고, 이미지, 테스트 대상이 아닌 GUI)를 동일하게 구성합니다. 아주 중요합니다. 가장 중요합니다!!!!!
-   모든 원고는 사용자가 쉽게 이해할 수 있는 용어로 서술합니다. 서비스의 전문 용어, 디자인의 전문 용어는 사용하지 않으며, 꼭 필요한 서비스 용어는 미리 설명합니다. 디자인 평가를 하게 하는 질문은 하지 않습니다. 우리가 측정하는 것은 KPI와 관련한 사용자 의도이지, 디자인 우수성을 평가하는 것이 아닙니다.
-   질문은 존대말을 사용하고, 현재형 질문을 사용합니다. (예: 만족하시나요? (O), 만족하셨나요?(X)), 골라주세요—\>선택해주세요.)
-   서비스의 사용 상황을 설명할 필요가 있으면 그 내용도 추가하여 설명합니다. 사용 상황에 알맞은 콘텐츠 원고를(시간, 지역, 상태 등) 제공합니다. (예: 당신은 11월에 혼자 도쿄 여행을 준비하고 있습니다.)
-   설문에서는 제시하는 서비스 페이지의 이미지를 중심으로 응답을 하므로 사용 경로(Flow) 중심의 검증은 한계가 있습니다. 화면 단위의 A/B 테스트 방법은 사용자 경로를 검증하기에는 적합하지 않습니다.
-   A안에 전혀 포함되지 않은 내용이나 디자인을 질문하지 않습니다. 두 개의 디자인에 대하여 객관적인 태도로 질문해야합니다.
-   설문에 제시하는 모바일 폰 테두리가 어색하지 않게 평가에 필요한 부분으로 스크롤한 이미지를 제시합니다. (사용자가 이해하기 어려운 긴 스크롤 뷰를 사용하지 않습니다.)
-   디자인 평가 대상이 아니어도 향후 디자인 개선을 위해 필요한 내용은 객관식이나 간단한 단답식 질문으로 추가 가능합니다. (평가 내용 2의 예: 검색 결과에 추가 되었으면하는 내용은 어떤 것인가요?) 또는 사용자의 타겟서비스 관련 행동을 질문할 수도 있습니다. (예: 사용하는 유사 서비스의 앱, 평소 일기쓰는 횟수 등의 질문)
-   사용자 구분이 필요한 경우에는 (예: heavy user와 light user의 구분) 조건에 맞는 사용자를 미리 선정하는 스크리닝을 실시하여 같은 조건의 사용자끼리만 비교해야합니다. 특히 A 디자인의 응답 그룹과 B 디자인의 응답 그룹이 매우 다른 성향이라면, 결과에 영향을 미치게 됩니다. A, B 응답자를 매우 다른 성향의 커뮤니티에서 따로 선정하거나, 나이, 성별, 연령 등이 확연히 다른 그룹으로 테스트하면 안됩니다.
-   자연스러운 사용자 시나리오를 중심으로 화면 순서를 배치하고, 각 화면에 관련한 질문(KPI 관련 질문, 추가 질문 모두)을 함께 배치합니다. 질문 번호는 1번부터 끝번까지 이어서 사용합니다. 화면이나 질문 카테고리별로 번호를 별도 부여하지 않습니다. 질문 섹션을 너무 많이 분리하면 설문 시간이 길어지고, 사용자들이 불편해할 수 있습니다.
-   구글 설문 폼은 리커트(Likert) 문항의 디자인 자유도가 제한적이므로 폰 화면에서 보이는 상태를 잘 고려하여 제작합니다.
-   설문 원고 제작과 내용 검수에 AI 서비스를 사용하는 것도 가능합니다. 설문 목표를 제시하고, 구체적인 질문원고와 선택지를 제안하게 하거나, 제작한 설문 원고에 문제가 없는지를 검토하도록 요청할 수 있습니다. AI를 사용할 때는 되도록 구체적으로 상황과 목표를 설명하고, 원고의 양식이나 예시등을 제시하여 응답의 정확도를 높이도록 합니다. 설문의 준비 과정과 결과 분석은 AI를 사용할 수 있지만, 설문 수행을 AI로 해서는 안됩니다. 우리는 디자인 검증을 위하여 실제 사용자의 의견을 필요로 합니다.
