project:
  type: book
  output-dir: docs

lang: ko-KR


book:
  title: "bitPublish를 이용하여 notionsample북만들기"
  chapters:
    - index.qmd
    - 1-1 UX 디자인의 오늘과 변화의 방향.qmd
    - 1-2 UX 디자인과 데이터, AI.qmd
    - 1-3 데이터 기반 디자인 (Data Driven Design).qmd


  cover-image: hexlogo/bitPublish_logo.png    
bibliography: references.bib
link-citations: false
keep-tex: false
citation_package: biblatex
biblatexoptions: [backend=biber,nohashothers=true, maxcitenames =2,bibstyle=authoryear,citestyle=authoryear]
            