# 머릿말: 이 책에서 다루는 것과 다루지 않는 것

안녕하세요. 데이터 기반 디자인과 A/B 테스팅의 세계에 방문하신 것을 환영합니다!

저는 여러분에게 이 책의 내용들을 경험할 수 있도록 안내할 홍익대 디자인컨버전스 학부 교수 이현진입니다. 이 책은 우리 학부의 3학년 전공 수업인 UX Design(2) 수업의 3년간 진행 경험을 기반으로 집필되었고, 앞으로 해당 수업에서 교재로 사용될 목적으로 제작했습니다. 이 책의 독자가 해당 수업을 수강하는 우리 학부 학생일 수도 있고, 관심 주제가 같은 다른 학교 디자인 전공 학생일 수도 있으며, 혹은 경험있는 디자인 실무자이거나 디자이너와 일하는 인접 분야의 전문가일 수도 있을 것으로 생각하고, 이 책에서 다루는 내용의 범위와 학습 내용에 대하여 먼저 안내를 드리고자 합니다.

이 책을 수업 교재로 사용하는 기준 독자는 UX 디자인 분야에 관심을 가지고, 디자인 방법론을 학습하고자 하는 학부 3학년 학생들입니다. 이 학생들은 권장 선수 과목 수업(UX Design(1))에서 더블 다이아몬드 모델 기반의 디자인 프로세스와 대면 리서치 형식의 사용자 관찰 및 인터뷰(Contexual Inquiry Interview)를 수행한 경험이 있고, 어피니티 다이어그램(Affinity Diagram) 기법으로 디자인 문제의 구조를 구축해봤으며, 디자인 콘셉트를 디지털 디바이스 (모바일 폰, 패드, 또는 여러 유형의 화면 디스플레이)의 GUI 디자인에 적용한 과제를 수행해 본 경험이 있습니다. 또한 일부 학생들은 이전 학기에 데이터 문해력 수업(Big Data)을 통하여 R 프로그래밍 기반의 데이터 분석 기법을 공부한 경험이 있기도 합니다. 그러나 이러한 선수 과목 수강이 필수 요건이 아니기 때문에 수강 인원의 절반 이상은 기초적인 그래픽 디자인과 인터렉션 디자인 관련 과목의 수강 경험 정도를 가지고 수업에 입문합니다. 그래서 이 수업에서는 디자인 프로세스 기초를 리뷰하는 시간도 갖고, 데이터 분석 경험이 없는 학생들을 위한 학습 경로도 제시합니다. 다만 독자 분들이 이상에서 설명한 선행 학습 주제에 대한 이해가 있으시다면 이 책의 핵심 내용을 더 빠르게 습득하실 수 있고, 만약 그렇지 않은 상태라면, 때에 따라서는 주제를 이해하는 데 필요한 기본 개념 들에 대하여 시간을 들여 보강해 가면서 공부하시면 좋겠다는 조언을 드립니다.

## 이 책에서 다루는 것:

-   모바일 플랫폼의 디지털미디어 서비스 디자인

이 책에서 주로 다루는 디자인 대상은 주로 모바일 폰과 같이 화면을 갖는 디지털 디바이스를 사용하는 서비스들 입니다. 플랫폼은 패드나 와치(Watch) 같이 다양한 크기일 수 도 있고, 웹 기반 또는 여러 모바일 OS를 기반으로 할 수도 있으나, 대부분 모바일 디지털 서비스들의 디자인을 대상으로 합니다. 책에서 다루는 디자인과 테스팅 방법들은 모바일 디바이스 외에 다른 플랫폼이나 서비스 형태에 적용하는 것도 가능하지만 학생들과 교수자의 관심 플랫폼이 모바일 서비스여서 수업에서는 주로 모바일 서비스를 디자인 대상으로 해왔습니다. 그래서 대부분의 예제는 모바일 앱을 사용하고 있습니다만, 학습 내용이 모바일 서비스에만 국한되는 것은 아니므로, 다른 제품 군이나 서비스를 대상으로 적용해도 문제는 없습니다.

-   데이터 기반 디자인 (Data Driven Design)

이 책의 주제는 디자인 과정에서 데이터, 특히 정량 데이터들을 활용하는 방법입니다. 서비스 플랫폼을 통하여 자동적으로 수집되는 서비스 로그 데이터나 사용자들을 대상으로 서비스에 대한 경험이나 의견을 묻는 설문 데이터를 분석하여 디자인에 대한 의사 결정을 하고, 수행한 의사 결정이 서비스의 목표에 부합하는 개선을 이루었는지를 통계적 방법으로 검증하는 방법을 학습합니다. 서비스의 실무 담당자가 아닌 학부생으로서 이런 문제를 다루는 데는 여러 제약이 존재하지만, 한정된 여건 속에서 데이터 기반 디자인이 수행되는 원리를 이해하고 실습해보는 경험을 가지며, 나아가 이 경험을 바탕으로 실무 디자인 상황에서 빠르게 데이터 기반 디자인 수행 능력을 갖추도록 하는 것이 본 교재의 목표입니다.

-   온라인 설문 조사 기법

데이터 기반 디자인을 위하여 설문 조사가 꼭 필요한 것은 아니고, 사용자 로그 데이터가 더 유용한 경우가 많지만, 실제 운영 중인 서비스의 데이터에 접근이 어려운 학부 수업의 상황을 고려하여 온라인 설문 조사를 통하여 서비스의 개선 디자인 검증 평가(A/B 테스팅)를 해오고 있습니다. 이를 위하여 다량의 정량 데이터 생성과 분석이 가능한 온라인 설문 수행 경험을 하고, 설문에서 분석한 주요 서비스 지표(KPI) 값들을 서비스의 디자인 해결안과 연결하여 사고하는 연습을 진행합니다.

-   린(Lean) 디자인 프로세스와 A/B 테스팅

교재에서 기반으로 하는 디자인 프로세스는 린(Lean) 디자인 프로세스 입니다. 이것은 데이터에 의한 정량적 가설 검증을 디자인 의사결정의 핵심 방법론으로 사용하고 있습니다. 본 수업의 실습 사례는 린 디자인 프로세스를 따라 진행되며, 디자인 의사결정이 필요한 때에 A/B 테스팅을 사용한 정량적 데이터 분석의 결과를 따릅니다. 다만 이 방법이 다른 방법보다 좋아서 선택했다기 보다는 데이터 기반 디자인 방법론과 잘 어울려 사용할 수 있기 때문에 린 디자인 프로세스를 선택한 것입니다. 그래서 본 교재를 통하여 린(Lean) 디자인 프로세스와 A/B 테스팅을 사용한 정량적 데이터 분석 방법을 주로 학습한다고 할 수도 있을 것 같습니다.

-   개선 디자인 프로젝트에 대한 디자인 리서치 포트폴리오

제공하는 전체 학습 과정을 정리 요약하면, 기존 서비스의 개선 디자인 프로젝트에 대한 디자인 리서치 포트폴리오를 완성할 수 있습니다. 본 실습 프로젝트는 기존에 운영 중인 서비스를 점진적, 반복적, 정량적으로 개선하는 과정을 실습하므로, 디자인 결과물의 참신성이나 창의성보다는 데이터 기반 디자인과 A/B 테스팅 기법을 활용한 방법론적 측면이 프로젝트의 차별점으로 보이게 될 것입니다. 그래서 본 교재의 학습 내용을 모든 디자인에 적용 가능한 일반적 방법론으로 보기 보다는 서비스 운영 중에 점진적인 디자인 개선을 목표로 하는 디지털 서비스에 적용하기 좋은 방법으로 인식하고, 이러한 특성에 맞는 실습 과제를 선택해서 진행해보는 것이 독자들에게 유용할 것으로 생각됩니다.

## 이 책에서 다루지 않는 것:

이 책에서는 디자인 교재라면 마땅히 포함되어 있을 법한 그래픽 디자인 관련 주제들은 다루지 않습니다. 브랜딩이나 캐릭터 디자인, 모션 그래픽과 같은 디자인 구성 요소를 디자인 해결안의 방향으로 사용하지 않습니다. 그 이유는 당연히 그런 디자인 방향이 의미가 없다는 뜻이 아니고, 이 교재에서는 주로 사용자 경험과 정보 구조, 정보의 레이아웃 등 UX, UI 디자인의 문제들을 발견하여 디자인 문제 해결을 하고자 하기 때문입니다. 그리고 UX 디자인에서 가장 중요한 방법론으로 인식되는 대면 사용자 연구도 다루지 않습니다. 사용자의 서비스 활용 현장에서 사용자를 관찰하고, 인터뷰하는 Contextual Inquiry Interview를 시행하지 않고, 대신 이미 수집된 사용자의 사용 경험 관련 데이터를 분석하고, 기존 서비스의 디자인 구성 요소들에 대한 분석을 실시합니다. 이 부분도 역시 대면으로 사용자 연구를 하는 것이 필요한 상황이 많이 있지만 교재의 학습 범위에 해당하지 않아서 시행하지 않는 것이므로, 마치 디자인 방법중에 데이터 기반 디자인만 하면 된다는 의도로 구성한 것이 아님을 이해해야합니다.

또한 독자들의 예상과 달리 데이터 분석을 위한 프로그래밍 학습도 심도있게 다루지 않습니다. 이 책은 디자인 방법론을 학습하는 책이므로 데이터 기반 디자인 방법론의 이해와 실습에 초첨을 맞추고 있습니다. 만약 이 책을 통하여 R이나 파이썬과 같은 데이터 분석을 위한 프로그래밍 기술과 분석 방법에 관심이 생겼다면 구체적인 데이터 문해력 학습은 다른 기회에 체계적으로 공부해야합니다. 그래서 이 책은 데이터 문해력이 갖추어진 학습자에게는 빠르게 학습할 수 있는 경로를 제공하고, 데이터 문해력이 낯선 학습자에게는 데이터 분석 기술이 부족한 상태에서도 진행할 수 있는 경로를 제공할 뿐 아니라, 향후 데이터 분석에 관심을 갖고 공부할 수 있도록 안내해주는 데 목적이 있습니다.

아무래도 책을 시작하려는 독자들 스스로 맞는 선택을 하고 있는지를 확인하도록 설명하려다 보니 말이 길어지고 있는데요, 독자 여러분들의 필요에 맞게 본 교재를 선택 하고, 경험하고 싶었던 내용들을 얻어 가셨으면 하는 바램입니다. 그럼 이후의 학습 내용들을 잘 활용하셔서 데이터 기반 디자인을 잘 수행할 수 있는 디자이너의 역량을 갖추시기 바랍니다.