# 디자인 리서치를 위한 탐구적 데이터 분석 사례 (1): 서울시 미세먼지 측정 데이터 분석 사례

앞 장에서 탐구적 데이터 분석 방법을 통하여 각 변수 별로 일반적인 값과
비정상적인 값의 상태, 변수 간의 상관관계와 구조를 확인할 수 있다고
하였습니다. 이번에는 실제 데이터의 탐구적 분석 사례를 통하여 변수와 값의
현황과 패턴을 어떻게 도출하는지 살펴보도록 하겠습니다.

## 미세먼지 정보 앱 디자인을 위한 미세먼지 데이터 분석 사례 개요

다음의 데이터 분석 사례는 서울의 미세먼지 현황과 예보를 사용자들의 정보
요구에 맞게 안내해주는 앱 서비스를 디자인한다는 가정하에 공공
데이터(Pulblic data)로 공개되어 있는 서울시 미세먼지 측정 데이터를
탐구적 데이터 분석 기법을 사용하여 미세먼지 정보 앱 서비스 디자인을 위한
디자인 인사이트를 도출한 사례입니다. 이 사례는 빅데이터의 탐구적 분석
결과를 어떻게 디자인에 반영할 수 있는지를 연구하고자 제작한 가상
사례입니다.

분석 사례에 사용한 공공 데이터는 다음과 같습니다.

-   서울 25개 측정소의 10년간 미세먼지 현황 데이터 (2008-2018년,
    10년간의 측정데이터)
-   2018년 서울 25개 구의 시간별 미세먼지 및 기타 오염물질 측정값
-   서울시 미세먼지/ 오염물질 측정소의 주소 정보
-   2018년 서울기상관측소의 날씨 데이터 (온도, 습도, 풍향)

여기에 서비스에 대한 사용자 니즈 관련 정보를 수집하기 위하여 목표
서비스와 비슷한 유사 앱 서비스에 대한 앱스토어의 사용자 평가 데이터
(‘미세미세’와 ‘에어비주얼’ 앱의 사용자 평가 데이터)도 분석하였습니다.

이 데이터들을 통하여 서비스의 사용자 니즈를 도출하고, 사용자의 미세먼지
정보 요구를 만족하기 위하여 미세먼지 현황과 미세먼지 예보 정보를 어떻게
제공해야 하는지를 데이터 분석을 통하여 발견하였고, 이 인사이트들을
앱디자인의 콘셉트에 반영하였습니다.

## 1) 유사 앱 서비스에 대한 앱스토어의 사용자 평가 데이터로 사용자 니즈 발견하기

다음의 \[표 1\]은 미세먼지 앱 ‘미세미세’, ‘에어비주얼’의 앱 스토어 평가
데이터 내용 및 언급 건수입니다. 앱의 디자인은 자주 업데이트 되고, 여러
버전의 디자인 평가가 섞이게 되면 신뢰성이 떨어지므로 연구 시점인
2021년에 운영중인 디자인 버전에 대한 평가 데이터를 수집했습니다. (데이터
수집 기간: 2021.3.1-2021.5.31)

사용자들의 앱 평가 내용을 사용자 정보 데이터와 앱 사용 시점 데이터,
평가에서 언급한 서비스 내용으로 분류하여 앱의 사용자 경험과 관련한 주요
키워드를 도출했습니다.

\[표 1\] 미세먼지 앱 ‘미세미세’, ‘에어비주얼’의 앱 스토어 평가 데이터
내용 및 언급 건수

+-----------+-----------+-----------+-----------+
| 주요      |           | 미세미세  | 에        |
| 데이터    |           | 앱        | 어비주얼  |
| 변수      |           | 평가내용  | 앱 평     |
|           |           | (총 188건 | 가내용(총 |
|           |           | 중 언급   | 109건 중  |
|           |           | 건수)     | 언급건수) |
+===========+===========+===========+===========+
| 사용자    | 질병      | 폐질환(2) | 육아(1)\  |
| 데이터    | /가족구성 |           | 타지역    |
|           | 등        |           | 친척      |
|           |           |           | 확인(1)   |
+-----------+-----------+-----------+-----------+
| 사용 상황 | 사용 시점 | 아침(3)\  | 해외 정보 |
| 데이터    | 등        | 외출(1)\  | 확인(3)   |
|           |           | 수        | 운동, 야  |
|           |           | 시확인(2) | 외활동(1) |
|           |           |           | 아침(2)\  |
|           |           |           | 환기(2)\  |
|           |           |           | 외출(2)\  |
|           |           |           | 수        |
|           |           |           | 시확인(4) |
+-----------+-----------+-----------+-----------+
| 서비스    | 서비스    | 접속      | 위치 표기 |
| 내용      | 불만 및   | 오류(9)\  | 오류(5)\  |
| 데이터    | 오류      | 위젯 불만 | 와치 연동 |
|           |           | /         | 오류(4)   |
|           |           | 오류(11)\ | 위젯      |
|           |           | 지도표기  | 오류(3)\  |
|           |           | 오류(11)  | 기타(3)   |
|           |           | 시간표기  |           |
|           |           | 오류(5)\  |           |
|           |           | 기타(7)   |           |
+-----------+-----------+-----------+-----------+
|           | 신뢰성    | 신        | 신        |
|           |           | 뢰함(16)\ | 뢰함(14)\ |
|           |           | 신뢰성    | 신뢰성    |
|           |           | 제기(8)   | 제기(1)   |
+-----------+-----------+-----------+-----------+
|           | 앱의 장점 | 편리한    | 편리한    |
|           |           | 디        | 디        |
|           |           | 자인(22)  | 자인(4)\  |
|           |           | 한눈에    | 한눈에    |
|           |           | 보임(9)\  | 보임(2)\  |
|           |           | 상세      | 상세      |
|           |           | 설명(6)\  | 설명(7)   |
|           |           | 캐릭터    | 지역      |
|           |           | 표현(8)\  | 정보(6)   |
|           |           | 알림(4)   | 바람 방향 |
|           |           |           | 정보(2)   |
+-----------+-----------+-----------+-----------+
|           | 가치평가  | 감사(29)\ | 감사(10)\ |
|           | (추천 /   | 좋음(41)\ | 좋음(28)\ |
|           | 감사 등)  | 잘 사     | 잘        |
|           |           | 용중(20)\ | 사        |
|           |           | 추천 /    | 용중(5)\  |
|           |           | 필수(14)  | 추천 /    |
|           |           |           | 필수(4)   |
+-----------+-----------+-----------+-----------+

앱 평가 키워드 분석을 통하여 제공 정보의 신뢰성과 정확성, 요약 설명과
상세 설명이 포함된 정보의 설명성이 중요한 가치라는 것을 발견했고,
신뢰성, 정확성, 설명성을 높이기 위하여 어떻게 정보를 제공해야하는지를
미세먼지 측정 데이터의 탐구적 분석을 통하여 알아보고자 합니다.

## 2) 서울시 미세먼지 측정 데이터에 대한 탐구적 분석 인사이트 도출

-   변수와 값의 개념

변수(Variable)는 데이터를 구성하는 각각의 항목을 의미합니다. 예를 들어,
사람의 키, 몸무게, 나이 등이 변수입니다. 이 데이터를 통해 다양한 정보를
얻을 수 있습니다. 이번에는 서울시 미세먼지 측정 데이터의 변수에 대해
알아보겠습니다. 값 (Value)은 변수가 가질 수 있는 실제 데이터를
의미합니다. 예를 들어, 사람의 키라는 변수의 값은 170cm, 180cm 등이 될 수
있습니다.

\[표 2\]를 보면 시간, 측정소 번호, 미세먼지 값, 초미세먼지 값 등의
변수에 2018-01-01 00:00:00, 101, 29, 17 과 같이 한 사례에 측정된 값들이
1행에 할당되어 있습니다. 그리고 각 값은 시간, 숫자, 텍스트 등의 표현
형식을 가지며, 표현 형식에 따라 분석 방법이나 분석 결과가 달라지게
됩니다. 이렇게 변수 별로 동일한 형식의 값을 여러 사례 수집한 데이터를
분석함으로써 우리는 측정 시간과 측정 장소 별 미세먼지 농도의 현황과 같은
유용한 정보를 얻을 수 있습니다.

\[표 2\] 서울시 미세먼지 측정 데이터(위)와 날씨 데이터(아래)의 변수 및
값의 형식

+-------+-------+-------+--------+----+-------+-------+
| 시간  | 측정소| 미세  | 초     | 월 | 시간  | 측정소|
| (월,  | 번호  | 먼지  | 미세   | (  | (시)  | 위치  |
| 일,   |       | 값    | 먼지   | 달 |       | (구)  |
| 시간) |       | (10pm)| 값     | )  |       |       |
|       |       |       | (2.5pm)|    |       |       |
+=======+=======+=======+========+====+=======+=======+
| 2018- | 101   | 29    | 17     | 1  | 0     | 종로구|
| 01-01 |       |       |        |    |       |       |
| 00:   |       |       |        |    |       |       |
| 00:00 |       |       |        |    |       |       |
+-------+-------+-------+--------+----+-------+-------+

서울 25개 측정소의 2018년 미세먼지 데이터 : 209,785개의 측정값 (서울
25개 측정소의 2008\~2018년 10년간 미세먼지 데이터 : 2,150,195개의
측정값도 같은 형식임.)

+-------+------+------+------+------+--------+
| 시간  | 기온 | 풍속 | 풍향 | 습도 | 풍향   |
| (월,  |      |      |      |      | 이름   |
| 일,   |      |      |      |      |        |
| 시간) |      |      |      |      |        |
+=======+======+======+======+======+========+
| 2018- | -3.2 | 0.5  | 110  | 40   | 동남동 |
| 01-01 |      |      |      |      |        |
| 00:   |      |      |      |      |        |
| 00:00 |      |      |      |      |        |
+-------+------+------+------+------+--------+
서울 기상 관측소 (108번 측정소)의 2018년 날씨 데이터 : 8,740개의 측정값

-   1년 간의 시간 변화에 따른 미세먼지량의 변화를 선 그래프로 표현한
    데이터 시각화 사례

\[표 2\]의 시간 변수와 미세먼지 값, 초미세먼지 값 변수에 대한 값의
변화를 그래프로 시각화하면 다음과 같습니다. 이 그래프를 보고 전체적으로
x축의 4월, 12월 주변 구간에서 측정량이 높게 나타나고, 여름에는
미세먼지량이 적게 나타나고 있어 미세먼지 측정량은 계절 차이가 있다고 할
수 있습니다. 전체적으로 미세먼지(빨강) 그래프가 위쪽에 자리하여 측정량이
많고, 측정량의 변동 폭도 큼을 볼 수 있습니다. 매우 높은 수치를 보여주는
지점들도 미세먼지 측정량(빨강)입니다. 그에 비하여 초미세먼지(파랑)는
변동이 작고 고르게 발생하고 있는 현황을 발견할 수 있습니다.

![2018년 서울시 미세먼지(적색)와 초미세먼지(청색)량의 측정값
현황](img/fig4.png)

-   2018년 1-5월의 월별 일간 미세먼지 측정량 변화폭을 표현한 데이터
    시각화 그래프 사례

아래 그림은 미세먼지가 검출량이 높은 1\~5월의 각 월별로 매일의 미세먼지
검출량의 범위가 드러나도록 한 그래프입니다. 막대 처럼 보이는 그래프
부분은 실제는 막대가 아니고 하루 동안의 미세먼지 측정량을 점으로 표현한
것이 모여서 막대처럼 보이고 있습니다. 시간 데이터 값을 월, 일로 분리하면
개별 하루의 측정 변화를 알아볼 수 있습니다. 이 그래프에서 4월 6일의
측정량 변화가 매우 큼을 확인하고, 4월 6일의 시간 별 측정 데이터를 시각화
하게 되었습니다.

![2018년 상반기(1-5월) 일별 미세먼지 측정량:미세먼지 시즌의 일별 측정량
변화를 보여준다. (회색 영역은 한국환경공단 기준 ‘미세먼지 나쁨’ 단계
범위](img/fig5.png)

-   2018년 4월 6일 하루 동안의 서울시 지역구별 미세먼지 측정량의 시각화
    그래프 사례

4월 6일의 미세먼지는 일간 변화량이 크고, 매우 나쁨 단계의 수치가 특정
시간대(오전 10시경\~오후11시경)에 집중되어 있습니다. 시간 별 측정량
차이가 크므로 미세먼지 대표값을 표현할 때 일평균 값을 쓰면 안된다는 것을
알 수 있습니다. 그리고 측정량을 꺾은선으로 표현할 때 점차 높아졌다가
낮아지는 흐름이 발견되므로 시간을 구간으로 나누어 측정량 예측 공지를 할
수 있을 것입니다.

측정소 지역별(구별) 특징을 보면 측정량을 다르지만, 시간별 측정 패턴이
다르지는 않아서 측정량의 흐름이 지역별로 동일하게 유지되고 있습니다.
매우 나쁨 단계의 측정량 범위(회색 영역 위쪽)가 너무 넓고, 같은 단계
안에서 측정량에 큰 차이가 존재합니다. 너무 넓은 변화 범위가 같은 단계로
표현되므로 매우 나쁨 단계를 더 나누어 세분화 표기할 필요가 있습니다.

![2018년 4월 6일(년간 미세먼지가 가장 심했던 날)의 시간별, 구별(지역별)
미세먼지 측정 현황(회색 영역은 한국환경공단 기준 ‘미세먼지 나쁨’
범위)](img/fig6.png)

-   서울시 지역구별 미세먼지 아주 나쁨 값이 관측된 횟수 비교 시각화 사례

아래 그림은 미세먼지 아주 나쁨 단계 값이 측정된 횟수를 비교한 막대
그래프입니다. 몇 개 지역은 미세먼지 아주 나쁨 상태가 더 자주 발생하고
있음을 알 수 있고, 지역별로 횟수 차이가 존재합니다. 그러므로 특정 지역에
거주하거나 방문하는 경우에는 좀 더 적극적으로 미세먼지 상황 정보를
제공할 필요가 있어 보입니다.

![2018년 서울시 지역구별 미세먼지 ‘아주 나쁨’ 기준 이상 값이 측정된
횟수](img/fig7.png)

본 사례에서는 예시와 같이 다양한 변수 별, 변수 간 데이터 시각화 실험을
통하여 25건의 미세먼지와 초미세먼지 관련 변수들의 현황과 관계 패턴 및
인사이트들을 발견할 수 있었습니다. 탐구적 데이터 분석 작업의 특징은
데이터의 변수 별, 변수 간 시각화를 순차적으로 해보고, 의미 해석을 한 뒤,
그 다음에 어떤 시각화를 진행할지를 작업 과정 중에 판단하고, 앞선
분석에서 제기된 질문에 대한 답을 구하면서 단계적으로 진행하는 특징이
있습니다. 데이터 분석의 순차적이고, 가변적인 작업 과정은 디자인 리서치의
방법에서도 공통적으로 발견되는 특징입니다.

### 3) 미세먼지 측정 데이터의 변수 현황 및 디자인 인사이트

\[표 3\]은 탐구적 데이터 분석을 통하여 발견한 서울시 미세먼지,
초미세먼지 데이터의 현황을 목록화하고, 각 결과를 바탕으로 디자인
인사이트를 도출한 사례입니다. 디자인 인사이트를 도출할 때는 1)의 사용자
니즈 발견에서 도출한 정보의 신뢰성, 정확성, 설명성 키워드를 연계하여
아이디어를 개발합니다.

\[표 3\] 미세먼지 및 초미세먼지 측정 데이터의 질문 사항과 분석 결과 및
데이터 패턴을 반영한 디자인 인사이트

+----------------+--------------------+--------------------+
| 주요 변수관련  | 분석 결과: 변수 별 | 데이터 변수 패턴을 |
| 데이터의 질문  | 값의 현황과 변수   | 반영하는 디자인    |
| 사항: 신뢰성,  | 간 상관관계        | 인사이트           |
| 데이터 제공    |                    |                    |
| 시점 ( 년      |                    |                    |
| ,월,일,시간)별 |                    |                    |
| 현황, 정보     |                    |                    |
| 설명성(요약,   |                    |                    |
| 상세(날씨,     |                    |                    |
| 지역)          |                    |                    |
+================+====================+====================+
| 미세먼지량과   | 대체로 양의        | 미세먼지와         |
| 초미세먼지량은 | 상관관계에 있으나  | 초미세먼지 데이터  |
| 서로 어떤      | 기준값 이상의      | 패턴이 다르므로    |
| 관계가 있는가. | 초미세먼지가       | 내용을 따로        |
|                | 기준값 이상의      | 표현하고, 각       |
|                | 미세먼지 보다 훨씬 | 패턴에 맞는 표현   |
|                | 자주 발생한다.     | 방법을 사용한다.   |
+----------------+--------------------+--------------------+
| 년간           | 각 해의            | 월별 미세먼지 발생 |
| 미세먼지와     | 상반기(4월)까지    | 시즌에 따라 다른   |
| 초미세먼지     | 먼지 발생이 높고,  | 표현으로 안내하는  |
| 현황은 어떤    | 5-10월까지는       | 정보 서비스가      |
| 특징을 가지나? | 발생량이 낮다가    | 필요하다. 발생량이 |
|                | 11월부터 높아진다. | 낮은 기간에는 앱   |
|                | 초미세먼지도 같은  | 사용도가 낮을      |
|                | 패턴을 보이며,     | 것이다.            |
|                | 일별 변동이 크다.  |                    |
+----------------+--------------------+--------------------+
| 월간           | 월 별 차이가 크다. | 초미세먼지 정보는  |
| 미세먼지와     | 초미세먼지도       | 연중 중요도가      |
| 초미세먼지     | 상반기가 많으나,   | 지속적으로 높고,   |
| 현황은 어떤    | 월별 먼지량의      | 대부분 나쁨        |
| 특징을 가지나? | 차이가 상대적으로  | 기준량을 초과하여  |
|                | 작다.              | 경각심을 줄 필요가 |
|                |                    | 있다.              |
+----------------+--------------------+--------------------+
| 미세먼지의     | 미세먼지가 많은    | 현재의 환경 공단   |
| 시간별 변화에  | 날은 특정 시간     | 기준 4단계 경보는  |
| 어떤 패턴이    | 대에 먼지량이      | 아주 나쁨 단계의   |
| 있는가?        | 집중되며, 아주     | 심각성을 반영하지  |
|                | 나쁨 수준에 매우   | 못한다. 단계       |
|                | 큰 편차가          | 구간의 변경이      |
|                | 존재한다. 기준     | 필요하다.          |
|                | 값보다 3-4배 많은  |                    |
|                | 날도 있다.         |                    |
+----------------+--------------------+--------------------+
| 초미세먼지의   | 초미세먼지가 많은  | 시간별 측정량을    |
| 시간 별 변화에 | 날은 특정 시간대에 | 강조하되, 일별     |
| 어떤 패턴이    | 먼지량이 집중되나  | 정보도 의미있게    |
| 있는가?        | 편차가 적다.       | 다룬다.            |
+----------------+--------------------+--------------------+
| 한국환경공단의 | 4단계로            | 정확한 정보 전달을 |
| 미세먼지 측정  | 되어있는데, 시간별 | 위해 미세먼지 측정 |
| 단계는 어떤    | 변동이 크므로 하루 | 단계 값을 일별     |
| 의미가 있나?   | 측정값의 평균을    | 국내 표준이 아닌   |
|                | 사용하는 표준 단계 | 더 정확한 단계로   |
|                | 값은 정확하지      | 제공해야           |
|                | 않다.              | 한다.(기존 앱도 더 |
|                |                    | 상세한 국제 기준을 |
|                |                    | 사용함)            |
+----------------+--------------------+--------------------+
| 미세먼지,      | 기온, 습도, 풍속은 | 풍향 정보가        |
| 초미세먼지와   | 크게 관련이 없고,  | 미세먼지 발생과    |
| 날씨는 어떤    | 서, 북향의 풍향이  | 연계되므로, 다른   |
| 관계가 있나?   | 많은 때에          | 날씨 정보보다 풍향 |
| 어떤 날씨      | 미세먼지,          | 정보를 잘 연계하여 |
| 정보가 영향을  | 초미세먼지 발생    | 표현해야 한다.     |
| 주나?          | 빈도가 높다.       |                    |
|                | 풍향은 계절(달)별  |                    |
|                | 먼지 발생에 영향을 |                    |
|                | 미친다.            |                    |
+----------------+--------------------+--------------------+
| 지역(측정소)별 | 서울시의 구별      | 지역별로 표현      |
| 미세먼지,      | 미세먼지 발생      | 방식이 다를 필요는 |
| 초미세먼지의   | 패턴은 유사하다.   | 없다. 그러나 발생  |
| 분포는         | 다만 특히 미세먼지 | 빈도가 높은 지역에 |
| 어떠한가?      | 나쁨 단계 이상     | 대한 경고 및       |
| 지역별 차별화  | 빈도가 큰 지역이   | 지역별 사용자      |
| 표현이         | 존재한다.          | 옵션으로 더 자세한 |
| 필요한가?      |                    | 미세먼지 정보를    |
|                |                    | 제공할 수 있다.    |
+----------------+--------------------+--------------------+

### 4) 데이터 변수 패턴 기반의 디자인 컨셉 도출

\[표 4\]는 프로젝트 데이터의 주요 변수와 키워드 별 변수 패턴을 반영한
디자인 콘셉트 제안 예시입니다. 앱 서비스에서 제공하는 정보 내용과 정보
제공 방법을 변수 패턴이 반영된 정보 표현 방법으로 제시하였습니다. 이러한
정보 표현 방법을 앱의 화면 레이아웃과 GUI에 반영하여 디자인 해결안을
완성하면, 탐구적 데이터 분석 기법을 디자인 리서치에 사용한 디자인
해결안이 됩니다.

\[표 4\] 프로젝트 데이터의 주요 변수와 키워드 별 변수 패턴을 반영한
디자인 콘셉트 제안 예시

+-------------+-------------+-------------+-------------+
| 주요 데이터 | 변수 관련   | 주요 변수   | 변수 패턴을 |
| 변수        | 키워드      | 패턴과      | 반영한      |
|             |             | 인사이트    | 디자인      |
|             |             |             | 콘셉트      |
+=============+=============+=============+=============+
| 사용자      | 질병/ 가족  | 특정 사용자 | \<서비스를  |
| 데이터      | 구성 등     | 집단별      | 자주        |
|             |             | 서비스      | 사용하는    |
|             |             | 니즈와 상관 | 사용        |
|             |             | 없이        | 자          |
|             |             | 서비스를    | \>서비스를  |
|             |             | 자주        | 자주        |
|             |             | 사용하는    | 사          |
|             |             | 사용자의    | 용하는(일별 |
|             |             | 필요 반영   | 사용 및     |
|             |             |             | 수시 사용)  |
|             |             |             | 일반        |
|             |             |             | 사용자를    |
|             |             |             | 타겟으로함. |
+-------------+-------------+-------------+-------------+
| 사용자 상황 | 사용 시점과 | 매일 및     | \<매일      |
| 데이터      | 빈도,       | 수시 확인   | 확인\> 일별 |
|             | 환경(날씨,  | 시점 별     | 통합 예측시 |
|             | 지역)       | 정보 니즈   | 시간대별    |
|             |             | 반영 환경   | 예측 정보   |
|             |             | 정보는 지역 | 제공 \<수시 |
|             |             | 상황에 따라 | 확인\> 측정 |
|             |             | 필요성이    | 시          |
|             |             | 다름 날씨는 | 점(시간별)  |
|             |             | 풍향만      | 정보,       |
|             |             | 미세먼지에  | 1-3시간 후  |
|             |             | 영향있음.   | 추이 정보   |
|             |             |             | 강조 사용자 |
|             |             |             | 선택        |
|             |             |             | 옵션으로    |
|             |             |             | 지역별      |
|             |             |             | 날씨,       |
|             |             |             | 미세먼지    |
|             |             |             | 상세 정보   |
|             |             |             | 제공        |
+-------------+-------------+-------------+-------------+
| 서비스 내용 | 정          | 년간 시 즌  | \<미세먼지  |
| 데이터      | 보의신뢰성/ | /월별/일별/ | 시즌 별     |
| (서비스     | 정확성 확보 | 시간별 발생 | 정보 표현   |
| 가치)       |             | 패턴이 다름 | 차별화\>    |
|             |             |             | 미세먼지    |
|             |             |             | 집중 기간   |
|             |             |             | (           |
|             |             |             | 11월-5월)과 |
|             |             |             | 그 외       |
|             |             |             | 기간의 정보 |
|             |             |             | 표현 차별화 |
|             |             |             | 여름 및     |
|             |             |             | 가을        |
|             |             |             | (           |
|             |             |             | 6-10월)에는 |
|             |             |             | 미세먼지    |
|             |             |             | 정보 외     |
|             |             |             | 부가 생활   |
|             |             |             | 정보 제공   |
|             |             |             | 시간별      |
|             |             |             | 측정량      |
|             |             |             | 중심의 정보 |
|             |             |             | 표현        |
+-------------+-------------+-------------+-------------+
|             | 정보 설명성 | 미세/초미세 | \<요약      |
|             | (요약, 상세 | 먼지의      | 설명\>      |
|             | 설명)       | 데이터      | 미세,       |
|             |             | 특징이 다름 | 초          |
|             |             | 일별 요약은 | 미세먼지의  |
|             |             | 대표값으로  | 표현 방법   |
|             |             | 부적절함    | 차별화 미세 |
|             |             | 미세먼지의  | 먼지의 아주 |
|             |             | 경우 아주   | 나쁨 단계   |
|             |             | 나쁨 단계   | 세분화      |
|             |             | 범위가 너무 | (초         |
|             |             | 넓음        | 미세먼지는  |
|             |             |             | 그대로      |
|             |             |             | 사용) 아주  |
|             |             |             | 나쁨 단계의 |
|             |             |             | 경각심 표현 |
|             |             |             | 강화 \<상세 |
|             |             |             | 설명\>      |
|             |             |             | 시간별 정보 |
|             |             |             | 중심으로    |
|             |             |             | 설명 사용자 |
|             |             |             | 옵션으로    |
|             |             |             | 사용자      |
|             |             |             | 요구에 따른 |
|             |             |             | 상세 설명   |
|             |             |             | 방법, 알림  |
|             |             |             | 방법 제공   |
+-------------+-------------+-------------+-------------+
|             | 관심 부가   | 알림, 위젯  | \<정보      |
|             | 서비스      | 등에서 요약 | 상황에 의한 |
|             |             | 정보 요구   | 알림/위젯   |
|             |             |             | 디자인\>    |
|             |             |             | 나쁨 빈도   |
|             |             |             | 높은        |
|             |             |             | 지역에는    |
|             |             |             | 알림 방법   |
|             |             |             | 강화 시간별 |
|             |             |             | 알림 및     |
|             |             |             | 관심 지역   |
|             |             |             | 중심의      |
|             |             |             | 알림, 위젯  |
|             |             |             | 디자인 제공 |
+-------------+-------------+-------------+-------------+

이렇게 디자인 리서치에서 데이터 분석 기법을 사용하면, 적은 노력으로
다량, 장기간의 데이터를 수집 분석하는 것이 가능하여 디자인 리서치의
생산성이 높아집니다. 탐구적 데이터 분석 방법은 대규모이거나 분야간
협업이 중요한 프로젝트에서도 소통 효율을 높이는 데 기여합니다.(7)

또한 이 사례와 같이 사용자에 대한 질적 연구 방법으로는 알 수 없는 콘텐츠
데이터(미세먼지 데이터)의 특징(신뢰성, 정확성, 설명성에 영향을 미치는
정보 속성들)을 데이터 분석 기법을 통하여 발견하고, 이를 디자인 콘셉트로
개발 할 수 있습니다. 이렇게 개발한 콘셉트로 디자인을 완성한 뒤에는 과연
이 디자인이 우리가 개선하고자 한 속성들(신뢰성, 정확성, 설명성)을
개선하였는지 검증해 볼 필요가 있겠죠. 이 검증 과정이 교재의 후반부에서
학습할 A/B 테스팅 입니다.

(문헌 7) 이현진, 『데이터 드리븐 디자인』, UX리뷰, (2024), pp.100-143
w