# 맺음말: 다음 테스트를 위하여

지금까지 데이터 기반 디자인과 Lean UX 디자인 프로세스, 디자인 검증을 위한 A/B 테스팅에 관한 이론들을 학습하고, 실습 과제들을 경험했는데요. 이제 데이터 기반 디자인에 대하여 이해가 되었다는 생각이 드시나요?

이상의 과정을 수업으로 진행하다 보면 여러가지 학생 피드백을 받게 됩니다. 가장 자주 듣는 말은 디자인하는 방법에 대한 새로운 경험을 갖게 되었다는 말입니다. 데이터 분석과 논리적 전개에 따라 시행되는 디자인은 기존에 해왔던 비교적 자유롭고, 감각적인 디자인 방법과는 차이가 있습니다. 하지만 실습 과제를 진행하면서 여전히 디자이너의 창의적 의사 결정 경로는 열려있다는 생각이 들지 않는지요? 잘 알다시피 과학이나 공학 분야도 매우 창의적인 사고가 필요합니다. 여러분이 얻은 새로운 경험을 통하여 데이터를 디자인 도구로 더 잘 사용할 수 있으면 좋겠습니다. 

두번째 많이 듣는 피드백은 A/B 테스팅을 하기 위해 컨트롤 해야하는 조건들의 제약이 크다보니, 디자인 자유도가 너무 적다, 이렇게 조금씩 개선하는 것이 답답하다는 것입니다. 이것도 맞는 말이고, 이렇게 진행하면 혁신적인 디자인을 반영하기는 어려운 점이 있습니다. 그래서 이 방법은 지속적인 개선을 전제로 하는 것입니다. 린 UX 디자인 방법은 적절한 조건의 프로젝트를 만날 때 효과가 큽니다. 모든 디자인을 해결하는 방법론이 아닙니다. 그래서 A/B  테스팅 이후의 개선 디자인 수정(B’ 디자인)을 실습할 때는 좀 더 자유롭고, 적극적인 디자인도 제안하도록 하여 디자이너가 느끼는 답답함을  해소하기도 합니다. 물론 린 UX의 점진적 개선 패러다임을 좀 벗어나게 되지요. 우리는 짧은 시간과 제한된 여건에서 디자인 방법을 이해하기 위한 연습을 해야하는 한계가 있음을 이해하기 바랍니다. 

서술한 바와 같이 데이터 기반 디자인은 나름대로의 장점과 한계를 갖고 있습니다. 마치 디자인을 할 때 각 표현 요소마다 사용하는 툴이 달라 질 수 있듯이, 내가 디자인하는 도구에 대한 또 하나의 선택지로서 데이터 기반 디자인을 이해하면 좋겠고, 이 도구는 기존의 디자인 방법에서 아쉬웠던 특별한 지점들을 채우기 위해 개발되었다고 생각하면 좋을 듯합니다. 또 데이터 기반 디자인은 오늘날의 산업 전반에서 정말 뜨거운 주제가 되어있는 인공지능 기술과 아주 잘 융합되는 특징을 지니고 있습니다. 데이터를 이해하고, 데이터로 소통하는 능력은 디자이너가 인공지능 관련 분야에 진입할 수 있는 기본 소양이라고 할 수 있습니다. 데이터 기반 디자인 역량이 매우 필요하다는 인식은 오래전 부터 있어왔지만, 데이터 기술을 이해하고 분석하는 능력의 장애물을 넘지 못해 디자인 영역으로 편입되기 어려웠습니다. 그러나 이제는 데이터 문해력의 대중화, 데이터 분석 도구들의 발전, 인공지능 기술과의 연계 등으로 기술적인 장애물의 높이는 많이 낮아졌고, 앞으로도 점점 더 낮아지는 추세입니다. 시대적 요구와 기술 환경이 준비 되었으니, 이제는 과감하게 데이터의 장애물을 건너 디자이너의 역량을 넓혀 봅시다. 가보지 않았던 길을 가 봄으로써 우리는 새로운 세계를 발견하게 될 것입니다. 

마지막으로 이 책에 담긴 다양한 디자인 사례와 실습 노하우를 축적할 수 있도록 기여해 준 우리 학부의 UX Design(2) 수업 수강생 여러분의 열린 마음과 디자인을 향한 노력에 감사를 전합니다. 그리고 뜻 깊게도 이 원고는 콘텐츠 원고를 데이터로 활용하여 web, e-bub, PDF 형태의 책으로 출판하는 R의 Quarto 서비스와 Bit Publish 소프트웨어를 사용하여 제작되었습니다. 책의 제작 과정을 통하여 데이터 기술의 또 다른 매력을 함께 경험할 수 있게되어 더욱 기쁩니다. 

본 교재의 학습 경험을 바탕으로 여러분의 다음 데이터 기반 디자인 프로젝트가 성공적인 결과를 내기를 기대해보며, 원고를 마치겠습니다.