# ch5. A/B 테스팅 결과의 디자인 반영

이제 실습 과제의 마지막 단계입니다. 우리는 실습 프로젝트에서 개선하고자 한 KPI가 개선 디자인(B안)을 통하여 개선 되었는지의 여부를 A/B 테스트로 확인했습니다. 이 결과를 어떻게 디자인에 반영해야 할까요? 다음의 사항들을 고려하여 디자인 반영 계획을 도출합니다.

-   테스트에서 KPI가 개선 되었음을 확인한 B안의 디자인 개선안들은 변경 확정을 합니다.

    다만 개선 디자인 부분들이 화면 경로의 앞, 뒤의 연계 화면에서 잘 이어지는지, 충돌의 여지가 있는지를 확인해야합니다. 같은 개선 디자인 요소가 반영되는 다른 화면들의 변경을 확정할 때도 다른 디자인 고려 사항이 있는지를 확인한 후에 변경 결정을 합니다.

-   테스트에서 KPI가 개선 되지 않은 부분은 원인 분석을 실시하여 개선 디자인을 수정(B’ 디자인)합니다.

    응답자 리크루팅, 질문 문항의 문구, 응답 선택지 디자인 등 테스트 설계가 잘못되었으면, 테스트를 수정하여 다시 실시해야하고, 개선 디자인에 문제가 있었으면, 개선 디자인을 변경해야 합니다. 또는 개선 디자인은 잘 진행 되었어도, 평가 대상이 아닌 다른 그래픽 요소 등에 영향을 받아 문제가 생길 수도 있습니다. 예를들어, 테스트 화면에 사용한 이미지의 크기나 이미지의 내용이 영향을 주어서 테스트 결과의 왜곡을 경험한 사례도 있습니다. 보통 모바일 화면 레이아웃에서 눈에 띄는 이미지를 사용하는 경우 응답자의 주의를 과도하게 분산하는 상황이 발생할 수 있습니다. 또 설문에서 수집한 데이터 내용을 참조하여 영향을 준 원인을 유추하는 것도 가능합니다. 이러한 원인들은 프로젝트의 성격에 따라 다양하게 나타납니다. 명확한 원인을 찾았다면 문제를 해결하여 테스트를 반복하면 되고, 원인이 불명확하다면 여러 가정에 따라 테스트 수정안을 여러가지로 준비하여 하나씩 확인해나가야 합니다.

-   그리고 KPI에 영향을 미치지 않는 요소라고 하더라도, 서비스의 전반적인 디자인 일관성이나 완성도 개선을 위해서, 또는 설문에서 추가적으로 제안된 사항에 대하여도 필요성을 판단하여 디자인 개선을 진행합니다.

    여기까지 디자인 개선 계획을 확정했다면, 이상적인 서비스의 흐름을 따라서 사용자 경험의 문제가 있는지를 검토하고, 디자인 개선을 완료합니다. 이제 린 디자인 프로세스에 의한 UX 디자인의 한 라운드 (Learn-Build-Measure-Learn)가 완료되었습니다.

-   린 디자인 프로세스는 반복적이고, 지속적인 프로세스입니다.

    기존 디자인(A 디자인)의 문제를 발견하고, KPI를 개선할 수 있는 개선 디자인(B 디자인)을 제시하여 두 디자인의 KPI 값에 대한 개선이 이루어졌는지를 측정하여 개선 디자인을 평가하는 한 라운드가 완료 되었지만, 실무적 입장에서는 타겟 서비스에 대한 린 디자인 프로세스가 이제 막 시작된 상태라고 할 수 있습니다. 이 프로세스는 목표한 KPI가 모두 개선될 때까지 디자인 수정을 시행하면서 테스트를 반복하게 될 것입니다. 그 외에 새로운 디자인 목표가 발생하거나, 비즈니스에 환경 변화가 있을 때 이 과정은 새로운 라운드를 시작하게 됩니다. 이 반복적인 개선과 검증의 순환은 서비스가 종료되는 시점까지 계속 모니터링 되고, 지속될 것입니다.

### 실습과제 11: 프로젝트의 최종 디자인 개선안 (디자인 B’) 제시

A/B 테스트의 결과를 반영한 최종 디자인 개선안(디자인 B’)를 제시합니다. B’ 디자인은 서비스의 실질적인 최종 디자인은 아닙니다. 새로운 디자인 개선안에 대하여 A/B 테스트를 했을 때 KPI 목표를 만족하지 못하거나 다른 디자인 문제가 발생할 수도 있고, 현 시점에서 디자인 확정이 되어도 향후에 지속적인 개선과 검증이 필요할 것이 때문입니다. 다만, 우리 실습 과제로서는 마지막 단계의 디자인 개선이므로 최종 디자인 개선안으로 표기하겠습니다.

-   KPI가 개선 되지 않았던 화면들의 디자인에 대하여 항목 별로 원인을 서술하고, 이를 디자인에 반영한 프로젝트의 최종 디자인 개선안(B’ 디자인) 화면을 제안합니다.

![\[그림 32\] 교통 약자를 위한 지하철 승강장 정보 화면에 대한 A/B 테스팅 결과와 B 디자인의 개선 방향 제안 예시](img/fig32.png)

-   기존 디자인(A 디자인), 개선 디자인(B 디자인), 최종 개선 디자인(B’ 디자인)의 화면들을 서로 비교하여 변화를 이해할 수 있게 서술합니다.

![\[그림 33\] \[그림 32\]의 프로젝트에 대한 기존 디자인 A,개선 디자인 B, 최종 디자인 B’ 화면의 디자인 비교 서술 예시](img/fig33.png)

-   최종 디자인(B’ 디자인)을 사용자의 사용 시나리오를 따라 제시하여 최종 디자인의 사용자 경험을 전체적으로 이해할 수 있도록 설명합니다.
-   필요하다면 최종 디자인(B’ 디자인)에 대한 검증 계획을 제안합니다. 이 테스트는 이미 수행한 개선 디자인(B 디자인) 테스트의 경험과 데이터를 활용하여 참여자, 문항, 선택지, 등의 요소들에 대한 다음 테스트 계획을 수립합니다. 예를 들어, 진행할 테스트의 문항이 이전 테스트와 동일한 경우에는 두번째 테스트에서 기존 디자인 (A 디자인)에 대한 평가를 새로 하지 않고, 이미 진행한 A 디자인 데이터와 새로 수집한 B’ 디자인 데이터를 비교하여 작업 부담을 줄일 수도 있고, 기존 디자인에 대한 설문을 추가로 시행한 뒤, 이전 설문의 데이터와 합쳐서 테스트 집단의 규모를 크게 할 수 도 있을 것입니다. 테스트가 반복될 수록 테스트의 수행 과정은 더 효율적으로 관리할 수 있고, 축적된 데이터들을 통하여 추가 인사이트들을 발견할 수 있습니다.

여기까지 데이터 기반 디자인과 A/B 테스팅의 실습과제들을 마치도록 하겠습니다. 실습에 참여하시느라 수고하셨습니다.
