# ch5. Lean UX 프로세스와 데이터 기반 디자인

### Lean Design Process의 개념

목표한 디자인 해결안을 완성하기까지 수행하는 디자인 활동의 내용과 방법, 과정을 정의하는 디자인 프로세스는 디자인의 대상과 사회, 기술적 요구 사항의 변화에 따라 변화하고 있습니다. 현대의 디자인 프로세스는 소프트웨어 기술과의 협업 과정, 비즈니스 방법의 변화에 영향을 받아 애자일(Agile) 디자인 프로세스, 린(Lean)디자인 프로세스라는 특별한 형식의 디자인 프로세스를 적용하는 사례가 많습니다.

‘Lean’이라는 단어가 ‘기대다’, ‘의지하다’라는 의미가 있고 ‘군살이 없는’ 이라는 의미도 있으므로, 린 디자인 프로세스는 편하게 기대어서 하는 디자인, 군살없이 날씬하게 진행하는 디자인 프로세스라는 의미로 생각해볼 수 있습니다. 결국 이 말은 디자인을 하는데, 쓸데 없는 일을 과하게 하지 않고, 시간과 비용의 효율을 추구하는 디자인 방법이라는 뜻입니다. 제품이나 서비스의 생산 주기가 짧고, 소규모 조직으로도 서비스 운영이 가능해진 현대 산업계의 특징을 반영하여 빠른 시간에 적은 인원을 가지고, 꼭 필요한 작업만을 효율적으로 해서 디자인을 수행하는 것이 린 디자인 프로세스의 철학입니다. 이러한 린(Lean) 철학을 UX 디자인 방법론에 가져온 것이 Lean UX입니다. 그러므로 Lean UX는 UX 디자인의 과정에서 시간과 자원을 효과적으로 사용하여 결과물을 산출하는 방법론이겠죠. UX 디자인 업무가 전통적으로 시간과 조직 역량을 많이 필요로 했던 문제를 해결하고자 한 방법론이라고 하겠습니다. 린 UX는 디자인의 효율화를 추구하는 핵심적인 전략으로 정량 데이터를 적극적으로 활용합니다.

‘린 스타트업 실전 UX’라는 책에서 저자(Laura Klein)는 린 UX에 대하여 Lean 비즈니스 환경에 적합한 UX 디자인을 말하는 것으로, 어떤 성과 지표(KPI: Key Performance Indicator)가 비즈니스를 이끄는지 알아내고, 이러한 지표를 개선하기 위해 해결해야할 고객의 문제가 무엇인지 이해하고(Hypothesis), 고객의 어려움을 개선하는 데 필요한 아이디어를 구현한 다음(MVP: Minimum Viable Product), 그게 적합한 아이디어인지 검증(A/B testing)하는 것이라고 설명했습니다. (20)

갑자기 낯선 용어들이 많이 나오죠? 괄호 안의 전문 용어들을 빼고 조금 쉽게 서술해 보면 린 UX는 어떤 비즈니스가 잘 되고 있는지를 측정하는 지표 값을 찾고, 이 값을 원하는 목표 값까지 달성하기 위하여 디자인을 수행한 뒤, 그 디자인이 성공했는지를 판단하기 위해 이전 디자인의 지표값과 개선 디자인의 지표값을 비교하여 평가한다는 의미입니다. 내용을 다시 해석해 보면 ‘지표 값’ 이라는 정량 데이터가 있고, 이 데이터를 ‘목표 값’의 정량 데이터로 변환 시키도록 디자인을 한 뒤, 디자인 개선 후의 ‘지표 값’이 ‘목표 값’ 수준으로 달성 되었는지를 정량적(통계적)으로 판단한다는 뜻이니, 전체적으로 정량 데이터의 측정과 평가를 중심으로 진행하는 디자인 방법론이네요. 그래서 Lean UX는 결국 데이터에 근거하여 디자인 의사 결정을 수행하는 데이터 기반 디자인 방법론의 하나입니다.

### Lean UX에 사용하는 주요 용어들

Lean UX를 수행하기 위하여 이해해야하는 KPI, Hypothesis, MVP, A/B 테스팅의 개념을 아래와 같이 정리하였습니다. 각각의 개념은 이후의 실습 프로젝트를 수행하면서 더 명확하게 이해할 수 있을 것입니다.

-   KPI(Key Performance Indicator)

    **KPI**는 조직이나 프로젝트의 목표 달성 정도를 측정하는 데 사용되는 핵심 성과 지표를 의미합니다. KPI를 통해 프로젝트의 진행 상황을 모니터링하고, 목표 달성을 위해 필요한 조치를 취할 수 있습니다. 예를 들어, 새로운 앱의 성공을 측정하기 위한 KPI로 월간 활성 사용자 수, 사용자 유지율, 평균 세션 시간 등을 KPI로 설정하고, 이 값으로 앱의 성과를 평가하고 필요한 개선점을 파악할 수 있습니다.

    주요 특징:

    1.  구체적이고 측정 가능함: 명확하고 구체적으로 정의되어야 하며, 수치로 측정 가능해야 합니다.
    2.  목표 지향적: 조직이나 프로젝트의 목표와 직접적으로 연결되어 있어야 합니다.
    3.  주기적 평가: 정기적으로 평가하여 진행 상황을 모니터링합니다.

-   Hypothesis

    **가설**은 특정한 질문이나 문제에 대한 예상 답변을 제시하는 것입니다. 제품이나 기능의 개발 전, 이를 통해 어떤 결과가 나올지를 미리 예측하고 테스트하는 과정을 의미합니다. Lean UX에서는 가설을 바탕으로 실험을 진행하고, 그 결과를 통해 제품을 개선합니다. 예를 들어, "앱의 새로운 알림 기능을 제공하면 앱을 더 자주 사용할 것이다"라는 가설을 세우고, 이를 테스트하기 위해 새로운 알림 기능을 출시한 후 사용자 반응을 분석합니다.

    주요 특징:

    1.  명확한 진술: 가설은 구체적이고 명확하게 진술되어야 합니다.
    2.  검증 가능: 실험을 통해 가설의 진위 여부를 확인할 수 있어야 합니다.
    3.  피드백 중심: 사용자 피드백을 통해 가설을 검증하고 개선.

-   MVP(Minimum Viable Product)

    **MVP**란 제품 개발 과정에서 최소한의 기능만을 갖춘 제품을 의미합니다. 이 제품은 사용자에게 실질적인 가치를 제공하면서도 개발에 소요되는 시간과 비용을 최소화하는 것이 목적입니다. MVP를 통해 빠르게 시장에 제품을 출시하고, 사용자로부터 피드백을 받아 제품을 개선해 나갈 수 있습니다.

    주요 특징:

    1.  최소한의 기능: 제품의 핵심 기능만 포함.
    2.  빠른 출시: 개발 시간을 줄여 빠르게 시장에 출시.
    3.  사용자 피드백: 실제 사용자로부터 피드백을 받아 제품을 개선.

-   A/B 테스팅

    A/B 테스트는 디자인의 구현 과정에서 화면이나 기능을 여러 버전으로 만들어서 서로 다른 사용자 그룹에 각기 다른 것을 보여주고 어떤 버전이 최선의 지표를 이끌어 내는지 찾아내는 기법입니다. A/B 테스트의 목적은 통계적으로 의미있는 데이터를 활용해서 사업적 중요성(KPI)을 기준으로 제품에 관련된 더 나은 의사결정을 하려는 것입니다. 예를 들어, 웹사이트의 버튼 색상을 A는 파란색, B는 빨간색으로 설정하여 어떤 색상이 더 많은 클릭을 유도하는지 테스트합니다.

    주요 특징:

    1.  두 가지 버전: A 버전과 B 버전, 두 가지 버전으로 나눔.
    2.  실험군과 통제군: 사용자 그룹을 나눠 각각 다른 버전을 사용하게 함.
    3.  성과 측정: 각 버전의 성과를 비교하여 더 나은 쪽을 선택.

### Lean UX Process Diagram (Learn\> Build \> Measure \> Learn \>의 반복)

데이터를 중심으로 의사결정을 하는 린 UX의 또 하나의 중요한 특징은 반복적인 수행 과정입니다.

데이터를 통하여 알게된(Learn) 인사이트를 가지고 KPI를 개선하는 아이디어(가설)를 내고, 이것을 MVP로 개발하여(Build) 아이디어가 잘 작동하는지는 검증(Measure)하고, 검증 데이터를 바탕으로(Learn) 다시 개선안을 내고, 이것을 MVP로 개발하여(Build) 아이디어가 잘 작동하는지는 검증(Measure)하는 반복적인 과정을 원하는 수준의 KPI에 도달할 때까지 반복하여 진행합니다. 최종 디자인 목표가 달성될 때까지 Learn\> Build \> Measure \> Learn \>의 과정은 반복됩니다. 이 과정을 그림으로 표현하면 \[그림 22\]과 같습니다.

애플은 앱 디자인 프로세스를 설명할 때 같은 개념을 Think\> Make\> Check\> Think의 반복적 프로세스로 설명했습니다.

![\[그림 22\] 순환적이고, 반복적인 Lean UX 디자인 프로세스](ch5 Lean UX 프로세스와 데이터 기반 디자인/22.png)

-   다음은 참고도서의 저자인 Laura Klein이 Lean UX에 대하여 설명하는 영상입니다.(21)

{{< video "https://www.youtube.com/watch?v=7NkMm5WefBA" >}}

우리는 Lean UX의 디자인 프로세스인 Leran \> Build \> Measure \> Learn의 단계를 따라서 실습 과제를 수행하게 됩니다. 그럼 다음 장에서는 Lean UX의 과정을 따라서 데이터 기반 디자인 방법을 실습해 볼까요?

(문헌 20) 로라 클라인, (김수영, 박기석 역), 『린 스타트업 실전 UX』, 한빛미디어,(2014)

(문헌 21) Google Developers, “UXD: What is Lean UX?”, https://www.youtube.com/watch?v=7NkMm5WefBA
